{
    "0": "Tiger Sign \"Stripelands\"",
    "2": "Tiger Sign \"Striped Menace\"",
    "4": "Tiger Sign \"Gold Jungle Tiger\"",
    "6": "Gold Sign \"Imitation Pagoda\"",
    "8": "Gold Sign \"Missing Pagoda in Myouren Temple\"",
    "9": "Gold Sign \"Trading Sequence\"",
    "10": "Large Ring \"Broken Umbrella\"",
    "12": "Large Ring \"A Forgotten Hindrance\"",
    "14": "Umbrella Sign \"Parasol Galaxy Musical\"",
    "16": "Umbrella Sign \"Parasol Galaxy Memories\"",
    "18": "Rain Sign \"Weeping Tear Storm\"",
    "20": "Umbrella \"Forgotten Umbrella in Rain\"",
    "22": "Monster Sign \"Midnight Train going Anywhere\"",
    "24": "Monster Train \"Train over Shallow Water\"",
    "26": "Iron Fist \"Hell's Fastest Fist\"",
    "28": "Divine Fist \"Hell Thrust from Space\"",
    "29": "Divine Fist \"Hell Thrust from Divinity\"",
    "30": "Fist Sign \"Ultimate Training Session\"",
    "32": "Barrage \"Sea Creature Training\"",
    "33": "Barrage \"King Neptune Strike\"",
    "34": "Hand Strike \"Knuckle Smash\"",
    "36": "Annihilation \"Heaven & Hell Smasher\"",
    "38": "Thunderous Yell \"Cloud-Filled Thunderstorm\"",
    "40": "Rage \"Fire Raining From Sky\"",
    "41": "Rage \"Last Day of Reckoning\"",
    "42": "Capsize \"Anchor Shot\"",
    "44": "Capsize \"Salvager Rank\"",
    "45": "Capsize \"Swimming Cloud Sea\"",
    "46": "Drowning Sign \"Floating Whirlpool\"",
    "48": "Drowning Sign \"Fluid Quicksand\"",
    "50": "Harbor Sign \"Abandoned Harbor\"",
    "52": "Harbor Sign \"Rotting Port\"",
    "53": "Harbor Sign \"Forgotten Ship's Port\"",
    "54": "Phantom \"Drowning Hallucination\"",
    "55": "Phantom \"Drowning Cycle\"",
    "56": "Phantom \"Drowning Cycle\"",
    "57": "Imitation Pagoda \"Desperate Light\"",
    "59": "Imitation Pagoda \"Desperate Light\"",
    "60": "Imitation Pagoda \"Desperate Light\"",
    "61": "Jeweled Pagoda \"Radial Lightsource\"",
    "63": "Jeweled Pagoda \"Flashing Lightgun\"",
    "64": "Jeweled Pagoda \"Flashing Lightgun\"",
    "65": "Light Sign \"Raining Lightbeams\"",
    "67": "Light Sign \"Unkown Lightsource\"",
    "69": "Buddhist Art \"Defiled Vajra Technique\"",
    "71": "Buddha's Light \"Vajra of Demon Ritual\"",
    "72": "Buddha's Light \"Vajra of Demon Ritual\"",
    "73": "Light Sign \"Makai Demon Purification\"",
    "75": "Light Sign \"Makai Demon Purification\"",
    "76": "\"Complete Purification\"",
    "77": "Magic \"Demonic Ominous Clouds\"",
    "79": "Demon Omen \"Forbidden Makai Magic\"",
    "80": "Demon Omen \"Makai's Demon Skills\"",
    "81": "Magic \"Makai Wildlife Preservation\"",
    "83": "Magic \"Makai Butterfly Swirl\"",
    "85": "Demon Magic \"Godly Laser Fight\"",
    "87": "Demon Magic \"Cheapshot Laser Problem\"",
    "88": "Demon Magic \"Cheapshot Laser Problem\"",
    "89": "Great Magic \"Grand Devil Finale\"",
    "91": "Great Magic \"Grand Devil Finale\"",
    "92": "Great Magic \"Grand Devil Finale\"",
    "94": "\"Makai Speed Enhancer\"",
    "95": "Superhuman \"Byakuren Hijiri's Biker Race\"",
    "96": "Forbidden Magic \"Mystic Square\"",
    "98": "Forbidden Magic \"Bizarre Romantic Story - Mystic Square\"",
    "99": "Forbidden Magic \"Bizarre Romantic Story - Mystic Square\"",
    "100": "Umbrella Sign \"Lightly Falling Large Raindrops\"",
    "101": "Surprising Rain \"Guerrilla Typhoon\"",
    "102": "Halo \"Karakasa Surprising Flash\"",
    "103": "Ominous Clouds \"Heian Dark Clouds\"",
    "104": "Unidentified \"Red UFO Invasion of Rage\"",
    "105": "Nue Sign \"Mysterious Snake Show\"",
    "106": "Unidentified \"Blue UFO Invasion of Grief\"",
    "107": "Nue Sign \"Danmaku Chimera\"",
    "108": "Unidentified \"Green UFO Invasion of Justice\"",
    "109": "Nue Sign \"Undefined Darkness\"",
    "110": "Unidentified \"Rainbow UFO Invasion of Terror\"",
    "111": "\"Nightmare of Heiankyou\"",
    "112": "Grudge Bow \"The Bow of Genzanmi Yorimasa\"",
    "93": "\"Amagimi Hijiri's Air Scroll\""
}