{
    "0": "Moon Sign \"Scarlet Moon Mist\"",
    "1": "Night Sign \"Night-Blind Bird\"",
    "2": "Darkness Sign \"Sphere of Shadows\"",
    "3": "Ice Sign \"Freezer-Burn\"",
    "4": "Hail Sign \"Frozen Spear\"",
    "5": "Freeze Sign \"Frozen Star\"",
    "6": "Snow Sign \"Mt. Avalance\"",
    "7": "Flower Sign \"Lovely Blooming Flower\"",
    "8": "Flower Sign \"Crossing Flower Field\"",
    "9": "Rainbow Sign \"Decorated Wall of China\"",
    "10": "Illusion Sign \"The Forest that never was\"",
    "11": "Colorful Sign \"Rainbow Hydra\"",
    "12": "Colorful Sign \"Choreographed Dance of Chaos\"",
    "13": "Colorful Sign \"Grand Branches of China\"",
    "14": "Fire Demon \"Agni Ember\"",
    "15": "Water Demon \"Underwater Undine\"",
    "16": "Wood Demon \"Sylphy Forest\"",
    "17": "Earth Demon \"Underground Trilithon\"",
    "18": "Metal Demon \"Rusty Metal\"",
    "19": "Fire Demon \"Agni Ember High Level\"",
    "20": "Wood Demon \"Sylphy Forest High Level\"",
    "21": "Earth Demon \"Underground Trilithon High Level\"",
    "22": "Fire Demon \"Agni Eruption\"",
    "23": "Water Demon \"Loch Ness Monster\"",
    "24": "Wood Demon \"Hidden Nymph\"",
    "25": "Earth Demon \"Trilithon Quake\"",
    "26": "Metal Demon \"Silver Lizard\"",
    "27": "Fire & Earth Demon \"Lava Plume\"",
    "28": "Wood & Fire Demon \"Forest Cinder\"",
    "29": "Water & Wood Demon \"Water Fairy\"",
    "30": "Metal & Water Demon \"Heavy Metal Poison\"",
    "31": "Earth & Metal Demon \"Emerald Mine\"",
    "32": "Conjuring \"Misdirecting Fool\"",
    "33": "Conjuring \"Intentional Misdirection\"",
    "34": "Illusion Existence \"Frozen Time\"",
    "35": "Illusion Image \"Fate of Luck\"",
    "36": "Maid Secret Skill \"Cross of Time\"",
    "37": "Illusion Phantom \"Ripples of Time\"",
    "38": "Illusion World \"Chaotic World\"",
    "39": "Maid Secret Skill \"Recursive Timeline\"",
    "40": "Suffocation \"Murder Room\"",
    "41": "Heaven's Punishment \"Bloodshed Cage\"",
    "42": "Nether Sign \"Scarlet Underworld\"",
    "43": "Curse \"Curse of Remilia Țepeș\"",
    "44": "Scarlet Sign \"Scarlet Wall\"",
    "45": "\"Blood Magic\"",
    "46": "God's Punishment \"Demon Anger\"",
    "47": "Hell Sign \"Prison of a Thousand Knifes\"",
    "48": "Divine Art \"Devil Claw Grip\"",
    "49": "Scarlet Sign \"Scarlet Devil Mansion Walls\"",
    "50": "\"Arrival of Remilia Scarlet\"",
    "51": "Moon Demon \"Quiet Monsoon\"",
    "52": "Sun Demon \"Solar Burst\"",
    "53": "Librarian Sign \"Little Demon Dance\"",
    "54": "Taboo \"Madness Prison\"",
    "55": "Taboo \"Bloody Lævateinn\"",
    "56": "Taboo \"Scarlet Devil Mansion Family\"",
    "57": "Taboo \"Prison Breaker\"",
    "58": "Taboo \"Love is but a Maze\"",
    "59": "Forbidden Barrage \"Wingbeat Crack\"",
    "60": "Forbidden Barrage \"Chaos Room\"",
    "61": "Forbidden Barrage \"Broken Flow of Time\"",
    "62": "Secret Barrage \"Who will be left, and who will die?\"",
    "63": "Q.E.D. \"Arrival after 495 Years\""
}