{
    "0": "Transmisson Sign \"Information Highway\"",
    "2": "Transmisson Sign \"Deeb-Webbed Transfer\"",
    "4": "Communication Sign \"SOS Message\"",
    "6": "Communication Sign \"High Alert! They are here!\"",
    "8": "Vessel Sign \"Emotional Ricochet\"",
    "10": "Vessel Sign \"Caged Emotion Chaos\"",
    "12": "Seperation Sign \"Losing Part of Yourself\"",
    "14": "Seperation Sign \"Fear of Eternal Loss\"",
    "16": "Imitation Sign \"Knife-Throwing Servants\"",
    "18": "Imitation Sign \"The Knife-Shaped Gap\"",
    "20": "Insanity Sign \"Maddening Cluster\"",
    "22": "Song Sign \"Enchanting Earworm\"",
    "24": "Song Sign \"Haunting Melody in your Mind\"",
    "26": "Empty Song \"Blank Music Sheet\"",
    "29": "Empty Song \"Newly Written Serenade\"",
    "30": "Mirage Sign \"Selfmade Duet Performance\"",
    "34": "Lunar Sign \"Reflecting Moon-Glow\"",
    "36": "Lunar Sign \"Reflecting Moon-Glow\"",
    "38": "Sun Sign \"Expanding Solar Burst\"",
    "40": "Sun Sign \"Dangerous Solar Flare\"",
    "42": "Vampire Sign \"Nightly Temperament\"",
    "44": "Vampire Sign \"Infernal Temperament\"",
    "46": "Knife Sign \"Illusionary Blade\"",
    "48": "Knife Sign \"Bladed Bird Cage\"",
    "50": "Creation Sign \"Divine Circulation\"",
    "54": "Shade Sign \"Admidst a Thousand Stars\"",
    "58": "Shadow Sign \"Creeping Suspicion\"",
    "62": "Sorrow Sign \"Haunting Rain\"",
    "66": "Eternal Vow \"Deep Promise\"",
    "68": "Eternal Vow \"Ever Lasting Bond\"",
    "70": "Connec's Dream \"Perfect Communication Technique\"",
    "73": "Connec's Dream \"Can she hear us?\"",
    "74": "Lunaa's Dream \"Freedom from Destiny\"",
    "76": "Lunaa's Dream \"She is using our Dreams!\"",
    "78": "Mari's Dream \"Fantastic Magical Research\"",
    "80": "Mari's Dream \"Let's wish for her Sanity to return!\"",
    "82": "Aternia's Dream \"Godly Redemption\"",
    "84": "Aternia's Dream \"I'm sorry, It was all my fault\"",
    "86": "Seraph's Dream \"Serene Time\"",
    "88": "Seraph's Dream \"Please come Home...\"",
    "90": "Shrine Maiden's Dream \"Faith and Donations\"",
    "94": "Fairy's Dream \"Fun-filled Life\"",
    "98": "Tengu's Dream \"The Biggest Scoop\"",
    "102": "Magician's Dream \"The Secret of Immortality\"", 
    "106": "Protection \"The Other Promise\"",
    "107": "Dirge Sign \"Vector to the Heavens\"",
    "108": "\"Unbreakable Chains\"",
    "109": "Vampire's Dream \"Mist-cloaked Gensokyo\"",
    "110": "Ghost's Dream \"Revival under the Tree\"",
    "111": "Lunarian's Dream \"End of Immortality\"",
    "112": "God's Dream \"Faith for all Gods\"",
    "113": "Raven's Dream \"Energy Revolution\"",
    "114": "Buddhist's Dream \"Cleansing of Hatred\"",
    "115": "Taoist's Dream \"Salvation of Nature\"",
    "116": "Inchling's Dream \"Respectful Society\"",
    "117": "Pure Dream \"Return of my Child\"",
    "118": "Jessica's Dream \"The Happiness of my Friends\""
}