{
    "0": "Transmisson Sign \"Information Highway\"",
    "2": "Transmisson Sign \"Deeb-Webbed Transfer\"",
    "4": "Communication Sign \"SOS Message\"",
    "6": "Communication Sign \"High Alert! They are here!\"",
    "8": "Vessel Sign \"Emotional Ricochet\"",
    "10": "Vessel Sign \"Caged Emotion Chaos\"",
    "12": "Seperation Sign \"Losing Part of Yourself\"",
    "14": "Seperation Sign \"Fear of Eternal Loss\"",
    "16": "Imitation Sign \"Knife-Throwing Servants\"",
    "18": "Imitation Sign \"The Knife-Shaped Gap\"",
    "20": "Insanity Sign \"Maddening Cluster\"",
    "22": "Song Sign \"Enchanting Earworm\"",
    "24": "Song Sign \"Haunting Melody in your Mind\"",
    "26": "Empty Song \"Blank Music Sheet\"",
    "29": "Empty Song \"Newly Written Serenade\"",
    "30": "Mirage Sign \"Selfmade Duet Performance\"",
    "34": "Magic Sign \"Instant Bodhi\"",
    "36": "Magic Sign \"Instant Bodhi\"",
    "38": "Magic Sign \"Bullet Golem\"",
    "40": "Magic Sign \"Gigantic Pet Bullet Lifeform\"",
    "42": "Jizo \"Criminal Salvation\"",
    "44": "Jizo \"Hellfire Salvation\"",
    "46": "Bamboo Sign \"Bamboo Spear Dance\"",
    "48": "Bamboo Sign \"Bamboo Crazy Dance\"",
    "50": "Myōga Ginger \"Forget Your Name\"",
    "54": "Broadleaf Sign \"Tanabata Star Festival\"",
    "58": "Myōga Blessing \"Behind You\"",
    "62": "Dance Sign \"Behind Festival\"",
    "66": "Mad Dance \"Tengu-odoshi\"",
    "68": "Mad Dance \"Frenzied Tengu-Frightening\"",
    "70": "Connec's Dream \"Perfect Communication Technique\"",
    "73": "Connec's Dream \"Can she hear us?\"",
    "74": "Lunaa's Dream \"Normal Sleep\"",
    "76": "Lunaa's Dream \"She is using our Dreams!\"",
    "78": "Mari's Dream \"Fantastic Magical Research\"",
    "80": "Mari's Dream \"Let's wish for her Sanity to return!\"",
    "82": "Aeternia's Dream \"Godly Redemption\"",
    "84": "Aeternia's Dream \"I'm sorry, It was all my fault\"",
    "86": "Seraph's Dream \"Normality in Life\"",
    "88": "Seraph's Dream \"Come back to us, you are our friend\"",
    "90": "Shrine Maiden's Dream \"Faith and Donations\"",
    "94": "Fairy's Dream \"Ultimate Strengh\"",
    "98": "Tengu's Dream \"The Biggest Scoop\"",
    "102": "Magician's Dream \"The Secret of Immortality\"", 
    "106": "Drum Dance \"Powerful Cheers\"",
    "107": "Mad Dance \"Crazy Backup Dance\"",
    "108": "Bullet Dance \"Twin Typhoons\"",
    "109": "Vampire's Dream \"Blood-Red Gensokyo\"",
    "110": "Ghost's Dream \"Revival under the Tree\"",
    "111": "Lunarian's Dream \"End of Immortality\"",
    "112": "God's Dream \"Faith for all Gods\"",
    "113": "Raven's Dream \"Energy Revolution\"",
    "114": "Buddhist's Dream \"Equality for All\"",
    "115": "Taoist's Dream \"Fulfillment of Desires\"",
    "116": "Inchling's Dream \"Respectful Society\"",
    "117": "Pure Dream \"Return of my Child\"",
    "118": "Jessica's Dream \"Shattered Wishes\""
}