{
    "0": "Firefly Sign \"Nightsky Nebula\"",
    "1": "Firefly Sign \"Nightsky Nebula\"",
    "2": "Swarm Sign \"Illusionary Group\"",
    "3": "Swarm Sign \"Illusionary Group\"",
    "4": "Swarm Sign \"Illusionary Group\"",
    "5": "Swarm Sign \"Illusionary Group\"",
    "6": "Wriggle Sign \"Fresh Cocoon\"",
    "7": "Wriggle Sign \"Hungry Caterpillar\"",
    "8": "Wriggle Sign \"Protective Sleep\"",
    "9": "Wriggle Sign \"Hatched Butterfly\"",
    "10": "Metamorphosis \"From Bug to Butterfly\"",
    "11": "Metamorphosis \"From Bug to Butterfly\"",
    "12": "Metamorphosis \"From Bug to Butterfly\"",
    "13": "Vocal Sign \"Silent Nightsky\"",
    "14": "Vocal Sign \"Silent Nightsky\"",
    "15": "Vocal Sign \"Ominous Hoot\"",
    "16": "Vocal Sign \"Ominous Hoot\"",
    "17": "Moth Sign \"Fresh Prey upon Claws\"",
    "18": "Moth Sign \"Fresh Prey upon Claws\"",
    "19": "Toxin Sign \"Dangerous Prey Decision\"",
    "20": "Deadly Toxin \"Unkown Nightly Demise\"",
    "21": "Hawk Sign \"Blindness of the Night\"",
    "22": "Hawk Sign \"Blindness of the Night\"",
    "23": "Hawk Sign \"Blindness of the Night\"",
    "24": "Hawk Sign \"Blindness of the Night\"",
    "25": "Night-Blindness \"Enchanting Sparrow Song\"",
    "26": "Night-Blindness \"Enchanting Sparrow Song\"",
    "27": "Night-Blindness \"Enchanting Sparrow Song\"",
    "28": "Night-Blindness \"Enchanting Sparrow Song\"",
    "29": "Night-Sparrow \"Midnight Chorus-Master\"",
    "30": "Night-Sparrow \"Midnight Chorus-Master\"",
    "31": "Night-Sparrow \"Midnight Chorus-Master\"",
    "32": "Ancient History \"Pyramids of Giza\"",
    "33": "Ancient History \"Pyramids of Giza\"",
    "34": "Ancient History \"Pyramids of Giza\"",
    "35": "Ancient History \"Pyramids of Giza\"",
    "36": "Origin Sign \"Volcanic Creationism\"",
    "37": "Origin Sign \"Volcanic Creationism\"",
    "38": "Origin Sign \"Volcanic Creationism\"",
    "39": "Evolution Sign \"Ancient Warfare\"",
    "40": "Evolution Sign \"Evolved Warfare\"",
    "41": "Evolution Sign \"Advanced Warfare\"",
    "42": "Evolution Sign \"From Swordfights to Gunfire\"",
    "43": "Land Sign \"Three Sacred Treasures - Sword\"",
    "44": "Land Sign \"Three Sacred Treasures - Orb\"",
    "45": "Land Sign \"Three Sacred Treasures - Mirror\"",
    "46": "Land Scheme \"Three Sacred Treasures - Country\"",
    "47": "Future Sign \"High-Tech Equipment\"",
    "48": "Future Sign \"High-Tech Equipment\"",
    "49": "Pseudo-Future \"Newfound Laser Suit\"",
    "50": "Pseudo-Future \"Newfound Laser Suit\"",
    "51": "Future \"Gods' Realm\"",
    "52": "Future \"Gods' Realm\"",
    "53": "Future \"Gods' Realm\"",
    "54": "Snowstorm Sign \"Brutal Mountain Winds\"",
    "55": "Snowstorm Sign \"Brutal Mountain Winds\"",
    "56": "Snowstorm Sign \"Fierce Snowstrike Tornado\"",
    "57": "Snowstorm Sign \"Fierce Snowstrike Tornado\"",
    "58": "Avalanche Sign \"Snowball Effect\"",
    "59": "Avalanche Sign \"Snowball Effect\"",
    "60": "Avalanche Sign \"Dangerous Ski Accident\"",
    "61": "Avalanche Sign \"Dangerous Ski Accident\"",
    "62": "Frozen Cavern \"Schneeberg Mystery\"",
    "63": "Frozen Cavern \"Schneeberg Mystery\"",
    "64": "Frozen Cavern \"Past Hidden Inside Ice\"",
    "65": "Frozen Cavern \"Trapped Ancient Civilization\"",
    "66": "Icicle Sign \"Self-Encasing Ice Armor\"",
    "67": "Icicle Sign \"Self-Encasing Ice Armor\"",
    "68": "Icicle Sign \"The Man Frozen in Ice\"",
    "69": "Icicle Sign \"The Man Frozen in Ice\"",
    "70": "Frozen Lake \"Surface Level Cracks\"",
    "71": "Frozen Lake \"Surface Level Cracks\"",
    "72": "Frozen Lake \"Shattered Layer of Ice\"",
    "73": "Frozen Lake \"Shattered Layer of Ice\"",
    "74": "Yukari's Highjack \"Frozen Butterfly Dash\"",
    "75": "Yukari's Highjack \"Frozen Butterfly Dash\"",
    "76": "Yukari's Highjack \"Frozen Butterfly Dash\"",
    "77": "Magic Sign \"Stardust Scatter\"",
    "78": "Magic Sign \"Stardust Scatter\"",
    "79": "Magic Space \"Andromeda Drift\"",
    "80": "Magic Space \"Andromeda Drift\"",
    "81": "Magic Sign \"Jupiter Drift\"",
    "82": "Magic Sign \"Jupiter Drift\"",
    "83": "Black Magic \"Quazar Expulsion\"",
    "84": "Black Magic \"Quazar Expulsion\"",
    "85": "Love Sign \"Lightray Photon\"",
    "86": "Love Sign \"Lightray Photon\"",
    "87": "Love Storm \"Star-Core Madness\"",
    "88": "Love Storm \"Star-Core Madness\"",
    "89": "Love Sign \"Master Spark\"",
    "90": "Love Sign \"Master Spark\"",
    "91": "Loving Heart \"Double Spark\"",
    "92": "Loving Heart \"Double Spark\"",
    "93": "Dim Dream \"Missile Ride\"",
    "94": "Dim Dream \"Missile Ride\"",
    "95": "Phantasmagoria \"Dream Spacetime Vessel\"",
    "96": "Phantasmagoria \"Dream Spacetime Vessel\"",
    "97": "Overheat \"Final Spark\"",
    "98": "Overheat \"Final Spark\"",
    "99": "Overheat \"Final Master Spark\"",
    "100": "Moon Sign \"Broken Moon Illusion\"",
    "101": "Moon Sign \"Broken Moon Illusion\"",
    "102": "Illusion Moon \"Half-Moon Night Sky\"",
    "103": "Illusion Moon \"Half-Moon Night Sky\"",
    "104": "Lunatic Sign \"Cross-Eyed Madness\"",
    "105": "Lunatic Sign \"Cross-Eyed Madness\"",
    "106": "Lunatic Gaze \"Maddening Eyes of Insanity\"",
    "107": "Lunatic Gaze \"Maddening Eyes of Insanity\"",
    "108": "War Sign \"Slow Day in the Trenches\"",
    "109": "War Sign \"Slow Day in the Trenches\"",
    "110": "Lunatic General \"Lunar War-Fields\"",
    "111": "Lunatic General \"Lunar War-Fields\"",
    "112": "Closed Quarters \"Last Man Standing\"",
    "113": "Closed Quarters \"Last Man Standing\"",
    "114": "Closed Quarters \"Last Man Standing\"",
    "115": "Closed Quarters \"Last Man Standing\"",
    "116": "Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
    "117": "Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
    "118": "Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"",
    "119": "Black Hole \"Hawking Radiation\"",
    "120": "Black Hole \"Hawking Radiation\"",
    "121": "Black Hole \"Event Horizon\"",
    "122": "Black Hole \"Event Horizon\"",
    "123": "Ozone Layer \"Protective Barrier\"",
    "124": "Ozone Layer \"Protective Barrier\"",
    "125": "Atmosphere Sign \"Disrupted Solar Winds\"",
    "126": "Atmosphere Sign \"Disrupted Solar Winds\"",
    "127": "Deep Space \"Background Radiation\"",
    "128": "Deep Space \"Background Radiation\"",
    "129": "Empty Space \"Antimatter Destruction\"",
    "130": "Empty Space \"Antimatter Destruction\"",
    "131": "Wormhole \"Theoretical Travel\"",
    "132": "Wormhole \"Theoretical Travel\"",
    "133": "Spacial Tear \"Spacetime Rift\"",
    "134": "Spacial Tear \"Spacetime Rift\"",
    "135": "Lunar Heavens \"Photon Particle Beam\"",
    "136": "Lunar Heavens \"Photon Particle Beam\"",
    "137": "Lunar Heavens \"Photon Particle Beam\"",
    "138": "Lunar Heavens \"Photon Particle Beam\"",
    "139": "Particle Accelerator \"Large Hadron Collider\"",
    "140": "Particle Accelerator \"Large Hadron Collider\"",
    "141": "Particle Accelerator \"Large Hadron Collider\"",
    "142": "Particle Accelerator \"Large Hadron Collider\"",
    "143": "Forbidden Elixir \"Hourai Elixir\"",
    "144": "Forbidden Elixir \"Hourai Elixir\"",
    "145": "Forbidden Elixir \"Hourai Elixir\"",
    "146": "Forbidden Elixir \"Hourai Elixir\"",
    "147": "Quazar Sign \"Powerful Star-Matter Beam\"",
    "148": "Quazar Sign \"Powerful Star-Matter Beam\"",
    "149": "Quazar Sign \"Powerful Star-Matter Beam\"",
    "150": "Quazar Sign \"Powerful Star-Matter Beam\"",
    "151": "Impossible Request \"Mechanical Angel's Wing\"",
    "152": "Impossible Request \"Mechanical Angel's Wing\"",
    "153": "Beloved Story \"Angel's Ultimate Sacrifice\"",
    "154": "Beloved Story \"Angel's Ultimate Sacrifice\"",
    "155": "Impossible Request \"Hidden Demon Possession\"",
    "156": "Impossible Request \"Hidden Demon Possession\"",
    "157": "Beloved Story \"Journey Over Stardust\"",
    "158": "Beloved Story \"Journey Over Stardust\"",
    "159": "Impossible Request \"Invasion From The Dragon Realm\"",
    "160": "Impossible Request \"Invasion From The Dragon Realm\"",
    "161": "Beloved Story \"Dangerous Dragon Livestyle\"",
    "162": "Beloved Story \"Dangerous Dragon Livestyle\"",
    "163": "Impossible Request \"Snowfall's Concert Lightshow\"",
    "164": "Impossible Request \"Snowfall's Concert Lightshow\"",
    "165": "Beloved Story \"Snow Halation\"",
    "166": "Beloved Story \"Snow Halation\"",
    "167": "Impossible Request \"Unkown God's Anger\"",
    "168": "Impossible Request \"Unkown God's Anger\"",
    "169": "Beloved Story \"The Dissapearance Of A God's Power\"",
    "170": "Beloved Story \"The Dissapearance Of A God's Power\"",
    "171": "\"End of Imperishable Night -New Moon-\"",
    "172": "\"End of Imperishable Night -Crescent Moon-\"",
    "173": "\"End of Imperishable Night -1st Quarter's Moon-\"",
    "174": "\"End of Imperishable Night -Matsuyoi-\"",
    "175": "\"End of Imperishable Night -11 o'Clock-\"",
    "176": "\"End of Imperishable Night -Half to Midnight-\"",
    "177": "\"End of Imperishable Night -Midnight-\"",
    "178": "\"End of Imperishable Night -Half Past Midnight-\"",
    "179": "\"End of Imperishable Night -1 o'Clock-\"",
    "180": "\"End of Imperishable Night -Half Past 1-\"",
    "181": "\"End of Imperishable Night -Dead of Night-\"",
    "182": "\"End of Imperishable Night -Half Past 2-\"",
    "183": "\"End of Imperishable Night -3 o'Clock-\"",
    "184": "\"End of Imperishable Night -Half Past 3-\"",
    "185": "\"End of Imperishable Night -4 o'Clock-\"",
    "186": "\"End of Imperishable Night -Half Past 4-\"",
    "187": "\"End of Imperishable Night -Morning Mist-\"",
    "188": "\"End of Imperishable Night -Dawn-\"",
    "189": "\"End of Imperishable Night -Morning Star-\"",
    "190": "\"End of Imperishable Night -Rising World-\"",
    "191": "Past \"Old History of an Untrodden Land -Old History-\"",
    "192": "Reincarnation \"Ichijou Returning Bridge\"",
    "193": "Future \"New History of Fantasy -Next History-\"",
    "194": "Limiting Edict \"Curse of Tsuki-no-Iwakasa\"",
    "195": "Undying \"Fire Bird -Feng Wing Ascension-\"",
    "196": "Fujiwara \"Wounds of Metsuzai Temple\"",
    "197": "Undying \"Xu Fu's Dimension\"",
    "198": "Expiation \"Honest Man's Death\"",
    "199": "Hollow Being \"Wu\"",
    "200": "Inextinguishable \"Phoenix's Tail\"",
    "201": "Hourai \"South Wind, Clear Sky -Fujiyama Volcano-\"",
    "202": "\"Possessed by Phoenix\"",
    "203": "\"Hourai Doll\"",
    "204": "\"Imperishable Shooting\"",
    "205": "\"Unseasonal Butterfly Storm\"",
    "206": "\"Blind Nightbird\"",
    "207": "\"Emperor of the Land of the Rising Sun\"",
    "208": "\"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)\"",
    "209": "\"Heaven Spider's Butterfly-Capturing Web\"",
    "210": "\"Tree-Ocean of Hourai\"",
    "211": "\"Phoenix Rebirth\"",
    "212": "\"Ancient Duper\"",
    "213": "\"Total Purification\"",
    "214": "\"Fantasy Nature\"",
    "215": "\"Blazing Star\"",
    "216": "\"Deflation World\"",
    "217": "\"Matsuyoi-Reflecting Satellite Slash\"",
    "218": "\"The Phantom of the Grand Guignol\"",
    "219": "\"Scarlet Destiny\"",
    "220": "\"Saigyouji Parinirvana\"",
    "221": "\"Profound Danmaku Barrier -Phantasm, Foam, and Shadow-\""
}