{
    "0": "Leaf Sign \"Disturbed Pile of Leaves\"",
    "2": "Fall Sign \"Deep-Red Fall Sky\"",
    "4": "Fall Sign \"Eternal Spirit of Autumn\"",
    "6": "Plenty Sign \"The Harvest Abundance\"",
    "8": "Bumper Crop \"Blessing from the Gods\"",
    "10": "Bad Luck Sign \"13 Bad Signs in a Day\"",
    "12": "Bad Luck Sign \"Black Cat's Evil Tail\"",
    "14": "Flawed Sign \"Shattered Mirror\"",
    "16": "Scar \"Shattered Mirror in the Sky\"",
    "18": "Evil Spirit \"Wheel of Destiny\"",
    "20": "Fate \"Fire in the Frozen Forest\"",
    "22": "Wound Sign \"Spilled Blood\"",
    "24": "Wound Sign \"Bloody Doll\"",
    "26": "Optics \"Invisibility Suit\"",
    "28": "Optics \"Hidden Machine in Snow\"",
    "30": "Flood \"Melting Icebergs\"",
    "32": "Flood \"Splitting Ice\"",
    "33": "Drown \"Meeting Marine Life\"",
    "34": "Water Sign \"Kappa's Torrent\"",
    "36": "Water Sign \"Kappa's Tsunami\"",
    "37": "Water Sign \"Kappa's Waterfall of the Sky\"",
    "38": "Kappa \"Cucumber Farm\"",
    "40": "Kappa \"Robotic Extend-O Arm\"",
    "41": "Kappa \"Spiiiiin the Kappaaaaaaa\"",
    "42": "Crossroad Sign \"Crossroads of Heaven\"",
    "44": "Crossroad Sign \"Saruta Cross\"",
    "46": "Wind God \"Wind God's Leaf-Veiling\"",
    "48": "Wind God \"Tengu's Fall Wind\"",
    "49": "Wind God \"Storm Day\"",
    "50": "\"Illusionary Dominance\"",
    "51": "\"Illusionary Dominance\"",
    "52": "\"Peerless Wind God\"",
    "53": "Blockade Sign \"Mountain God's Procession\"",
    "55": "Blockade Sign \"Advent of the Divine Grandson\"",
    "56": "Blockade Sign \"Terukuni Shining Through Heaven and Earth\"",
    "57": "Esoterica \"Gray Thaumaturgy\"",
    "59": "Esoterica \"Forgotten Ritual\"",
    "60": "Esoterica \"Secretly Inherited Art of Danmaku\"",
    "61": "Miracle \"Daytime Guest Stars\"",
    "63": "Miracle \"Night with Bright Guest Stars\"",
    "64": "Miracle \"Night with Overly Bright Guest Stars\"",
    "65": "Sea Parting \"The Day the Sea Split\"",
    "67": "Sea Parting \"Moses' Miracle\"",
    "68": "Sea Parting \"Moses' Miracle\"",
    "69": "Preparation \"Star Ritual to Call the Godly Winds\"",
    "71": "Preparation \"Summon Takeminakata\"",
    "73": "Miracle \"God's Wind\"",
    "75": "Great Miracle \"Yasaka's Divine Wind\"",
    "77": "Divine Festival \"Expanded Onbashira\"",
    "79": "Weird Festival \"Medoteko Boisterous Dance\"",
    "80": "Weird Festival \"Medoteko Boisterous Dance\"",
    "81": "Rice Porridge in Tube \"God's Rice Porridge\"",
    "83": "Forgotten Grain \"Unremembered Crop\"",
    "84": "Divine Grain \"Divining Crop\"",
    "85": "Sacrifice Sign \"Misayama Hunting Shrine Ritual\"",
    "87": "Mystery \"Kuzui Clear Water\"",
    "88": "Mystery \"Yamato Torus\"",
    "89": "Heaven's Stream \"Miracle of Otensui\"",
    "91": "Heaven's Dragon \"Source of Rains\"",
    "93": "\"Mountain of Faith\"",
    "95": "\"Divine Virtues of Wind God\"",
    "97": "God Sign \"Beautiful Spring like Suiga\"",
    "98": "God Sign \"Ancient Fate Linked by Cedars\"",
    "99": "God Sign \"Omiwatari that God Walked\"",
    "100": "Party Start \"Two Bows, Two Claps, and One Bow\"",
    "101": "Native God \"Lord Long-Arm and Lord Long-Leg\"",
    "102": "Divine Tool \"Moriya's Iron Ring\"",
    "103": "Spring Sign \"Jade of the Horrid River\"",
    "104": "Frog Hunt \"The Snake Eats the Croaking Frog\"",
    "105": "Native God \"Seven Stones and Seven Trees\"",
    "106": "Native God \"Froggy Braves the Wind and Rain\"",
    "107": "Native God \"Red Frogs of Houei Four\"",
    "108": "\"Suwa War ~ Native Myth vs. Central Myth\"",
    "109": "Scourge Sign \"Mishaguji-sama\""
}