{
    "0": "Leaf Sign \"Disturbed Pile of Leaves\"",
    "2": "Fall Sign \"Deep-Red Fall Sky\"",
    "4": "Fall Sign \"Eternal Spirit of Autumn\"",
    "6": "Plenty Sign \"The Harvest Abundance\"",
    "8": "Bumper Crop \"Blessing from the Gods\"",
    "10": "Bad Luck Sign \"13 Bad Signs in a Day\"",
    "12": "Bad Luck Sign \"Black Cat's Evil Tail\"",
    "14": "Flawed Sign \"Shattered Mirror\"",
    "16": "Scar \"Shattered Mirror in the Sky\"",
    "18": "Evil Spirit \"Wheel of Destiny\"",
    "20": "Fate \"Fire in the Frozen Forest\"",
    "22": "Wound Sign \"Spilled Blood\"",
    "24": "Wound Sign \"Bloody Doll\"",
    "26": "Optics \"Invisibility Suit\"",
    "28": "Optics \"Hidden Machine in Snow\"",
    "30": "Flood \"Melting Icebergs\"",
    "32": "Flood \"Splitting Ice\"",
    "33": "Drown \"Meeting Marine Life\"",
    "34": "Water Sign \"Kappa's Torrent\"",
    "36": "Water Sign \"Kappa's Tsunami\"",
    "37": "Water Sign \"Kappa's Waterfall of the Sky\"",
    "38": "Kappa \"Cucumber Farm\"",
    "40": "Kappa \"Robotic Extend-O Arm\"",
    "41": "Kappa \"Spiiiiin the Kappaaaaaaa\"",
    "42": "Crossroad Sign \"Heaven-Blocking Winds\"",
    "44": "Crossroad Sign \"Heavenly Crossing\"",
    "46": "Wind God \"Saw Hidden In Leaves\"",
    "48": "Wind God \"Chainsaw Hidden In Forest\"",
    "49": "Wind God \"Destructive Tornado\"",
    "50": "\"Speed Coverage - Aya Shameimeru\"",
    "51": "\"Speed Coverage - Aya Shameimeru\"",
    "52": "\"Ultimate Double Spoiler\"",
    "53": "Blockade Sign \"Frozen Waterfall Barrier\"",
    "55": "Blockade Sign \"Unkown Gods Shield\"",
    "56": "Blockade Sign \"Shining Sun Gleaming Over Mountains\"",
    "57": "Esoterica \"Starshine Ritual\"",
    "59": "Esoterica \"Celestial Barrage\"",
    "60": "Esoterica \"Secret Ritual of Ancient Times\"",
    "61": "Miracle \"Visible Daytime Star\"",
    "63": "Miracle \"Brightest Nightstar\"",
    "64": "Miracle \"Most Beautiful Starry Night\"",
    "65": "Sea Parting \"Cursed Desert Under Sea\"",
    "67": "Sea Parting \"False Prophets Lie\"",
    "68": "Sea Parting \"False Prophets Lie\"",
    "69": "Preparation \"Perfect Wind-Summoning Ritual\"",
    "71": "Preparation \"Blessing To The Gods\"",
    "73": "Miracle \"Godly Typhoon\"",
    "75": "Great Miracle \"Yasaka's Beautiful Blessing\"",
    "77": "Divine Festival \"Ultimate Onbashira\"",
    "79": "Weird Festival \"Divine Summoning Dance\"",
    "80": "Weird Festival \"Divine Summoning Dance\"",
    "81": "Rice Porridge in Tube \"Perfect Rice Storage\"",
    "83": "Forgotten Grain \"Fantastic Crop Gain\"",
    "84": "Divine Grain \"Holy Crop\"",
    "85": "Sacrifice Sign \"Miasma-Filled Moon\"",
    "87": "Mystery \"Sharp Rain Torrent\"",
    "88": "Mystery \"Starsign Finder\"",
    "89": "Heaven's Stream \"Windy Storm\"",
    "91": "Heaven's Dragon \"Thunderstorm Clouds\"",
    "93": "\"Artificial Faith Machine\"",
    "95": "\"Machine of New Era\"",
    "97": "God Sign \"Beautiful Spring like Suiga\"",
    "98": "God Sign \"Ancient Fate Linked by Cedars\"",
    "99": "God Sign \"Omiwatari that God Walked\"",
    "100": "Party Start \"Two Bows, Two Claps, and One Bow\"",
    "101": "Native God \"Lord Long-Arm and Lord Long-Leg\"",
    "102": "Divine Tool \"Moriya's Iron Ring\"",
    "103": "Spring Sign \"Jade of the Horrid River\"",
    "104": "Frog Hunt \"The Snake Eats the Croaking Frog\"",
    "105": "Native God \"Seven Stones and Seven Trees\"",
    "106": "Native God \"Froggy Braves the Wind and Rain\"",
    "107": "Native God \"Red Frogs of Houei Four\"",
    "108": "\"Suwa War ~ Native Myth vs. Central Myth\"",
    "109": "Scourge Sign \"Mishaguji-sama\""
}