{
    "2": "Gun Sign \"Rapid-Fire Shooting\"",
    "3": "Sugar Sign \"Dango Wall\"",
    "4": "Gun Sign \"A Gun to your Head\"",
    "5": "Sugar Sign \"Dango Hurricane\"",
    "7": "Butterfly Sign \"Butterfly Nightmare\"",
    "8": "Butterfly Sign \"Infinite Scales\"",
    "10": "Magic Sign \"Relentless Jizo\"",
    "11": "Jizo \"Stomping a Dead Bug\"",
    "12": "Jizo \"Murderous Bullet Titan\"",
    "14": "Assasination Sign \"Three Knives in your Back\"",
    "15": "Murder Sign \"Thick Path of Knives\"",
    "17": "Fake Border \"Curved Border of Hakurei's Dog\"",
    "18": "Dog Sign \"Protector of Hakurei\"",
    "21": "War Sign \"Assault in the Barracks\"",
    "22": "\"Ringo and the Dango Factory\"",
    "23": "Nightmare Butterfly \"Metamorphosis\"",
    "24": "Nightmare Jizo \"Flames rising from the Snowy Forest\"",
    "25": "Nightmare Blade Maniac \"Killer's Dream Visit\"",
    "26": "Nightmare Dog \"Bite your Neck\"",
    "28": "Hell Sign \"Death's Triangle\"",
    "29": "Hell Sign \"Double Stripe\"",
    "30": "Moon Chaos \"Close-orbiting Death Moon\"",
    "32": "Orb Sign \"The Great Wall of the Lunar Capital\"",
    "33": "Orb Sign \"Machine-gun Coronation of the Gods\"",
    "34": "Nightmare Heron \"High-Speed Heron Flight\"",
    "36": "Bamboo Sign \"Bamboo Forest of the Lost\"",
    "37": "Myōga Ginger \"Quick-step Backdance\"",
    "38": "\"Shining Shooting Star-Festival\"",
    "39": "\"Unkown Being stalking behind you\"",
    "41": "Otherworld \"Hell's Fire of the Past\"",
    "42": "Otherworld \"Hell's Heavy Flame Geyser\"",
    "43": "Moon \"Distance-Measuring Lasers\"",
    "44": "Otherworld \"Ōmagatoki -Nightmare-\"",
    "45": "\"Catastrophic Planet Sized Meteor-Impact!\"",
    "47": "\"Anxiety Inducing Trauma\"",
    "48": "\"Psychedelic Mandala\"",
    "49": "\"Purest Light as seen through Glasses\"",
    "50": "\"Danmaku for Killing with Certainty via Nightmares\"",
    "51": "Secret Ceremony \"Hidden Stars Behind your Back\"",
    "52": "Secret Ceremony \"Burning Fire of the Back Door\"",
    "53": "Back Sign \"All Around Laser Halo\"",
    "54": "Secret Ceremony \"Secret God's All Consuming Darkness\"",
    "55": "Secret Ceremony \"Arcadia Duplication\"",
    "57": "Scarlet Devil Sign \"Bloody Massacre\"",
    "61": "Divine Scarlet Sign \"Bloody Laser of Inifinte Articles\"",
    "62": "Scarlet Star Sign \"Superhuman Massacre Journey\"",
    "64": "Wind God Sign \"Mountain of Faith\"",
    "66": "Wind Flower Sign \"Mishaguji-sama's Wrong Trial\"",
    "68": "Wind Flower Sign \"Onbashira Execution\"",
    "72": "Shining Night Sign \"Massive Danmaku Branch of Hourai\"",
    "70": "Scarlet Needle Sign \"Parts of Heaven Grow Massive!\"",
    "69": "Eternal Night Sign \"Danmaku Branch of Hourai in a Boiling Pot\"",
    "74": "Scarlet Night Sign \"Danmaku Heaven of Hourai\"",
    "75": "Earth Spirit Sign \"Explosive Mind Stealer\"",
    "76": "Earth Mystic Sign \"Nine-Tailed-Shikigami of the Id\"",
    "77": "\"Robbery of Thought and Subconcious\"",
    "78": "Earth Mystic Sign \"Shikigami's Supernova\"",
    "80": "Earth Spirit Sign \"Mind's Stellar Trauma\"",
    "81": "Divine Star Sign \"Unidentified Crowd Passing Through a Path\"",
    "82": "Shining Heaven Sign \"Thunderstorm High-Class Drumset\"",
    "83": "Shining Divine Sign \"Crowded Rock-Concert\"",
    "84": "Scarlet Star Sign \"Unidentified Thunderstorm\"",
    "85": "Divine Scarlet Sign \"Struck By Lightning\"",
    "86": "Shining Star Sign \"Unidentified High-Class Drumset\"",
    "87": "Gathering Night Sign \"Precious Life fades away like Mist\"",
    "88": "\"First and Last Nameless Danmaku\"",
    "91": "Gathering Orb Sign \"Foggy Moon Surface\"",
    "92": "Eternal Orb Sign \"Resentful Grudges against Rivals\"",
    "93": "\"Secret God Boundaries\"",
    "96": "\"Shoot the Trapped Victim!\"",
    "94": "\"Social-Media-Exposer Exorcism Master Spark\"",
    "99": "\"Doremy Sweets Dream Dweller Elimination\"",
    "100": "Paper Sign \"Dreamful ESP-Cards\"",
    "101": "\"Boundary Breaking Psychic\"",
    "58": "Star Divine Sign \"Superhuman of Infinite Articles\"",
    "59": "Scarlet Star Sign \"Superhuman's Bloody Chainsaw\"",
    "60": "Scarlet Divine Sign \"Massacre of Infinite Articles\"",
    "63": "Mystic Flower Sign \"Butterfly Tornado Yama Judgement\"",
    "65": "Wind Mystic Sign \"Killing Butterfly Onbashira\"",
    "67": "Mystic Wind Sign \"Native Butterfly Tornado\"",
    "71": "Eternal Scarlet Sign \"Plummeting Bhava-agra in a Boiling Pot\"",
    "73": "Eternal Shining Sign \"Boiling Pot Growing Massive\"",
    "79": "Earth Mystic Sign \"Shikigami of the Ego\"",
    "89": "Gathering Orb Sign \"Pure Mist Fading into Nothingness\"",
    "90": "Eternal Orb Sign \"Reckless Sacrifice's Hell Journey\"",
    "95": "\"Social-Media-Exposer Exorcism from the Back\"",
    "97": "\"Master Spark From the Back Door\"",
    "98": "\"The Two Layers of the Border\""
}