{
    "2": "Gun Sign \"Rapid-Fire Shooting\"",
    "3": "Sugar Sign \"Dango Wall\"",
    "4": "Gun Sign \"A Gun to your Head\"",
    "5": "Sugar Sign \"Dango Hurricane\"",
    "7": "Butterfly Sign \"Butterfly Nightmare\"",
    "8": "Butterfly Sign \"Infinite Scales\"",
    "10": "Magic Sign \"Relentless Jizo\"",
    "11": "Jizo \"Stomping a Dead Bug\"",
    "12": "Jizo \"Murderous Bullet Titan\"",
    "14": "Assasination Sign \"Three Knives in your Back\"",
    "15": "Murder Sign \"Thick Path of Knives\"",
    "17": "Fake Border \"Curved Border of Hakurei's Dog\"",
    "18": "Dog Sign \"Protector of Hakurei\"",
    "21": "Dream Bullet \"Lunatic Dream Shot\"",
    "22": "Dango \"Dango Flower\"",
    "23": "Dream Butterfly \"Crazy Butterfly\"",
    "24": "Dream Jizo \"Kalpagni's Hope\"",
    "25": "Dream Blade Exhaustion \"Demonic Killer's Retreat\"",
    "26": "Dream Dog \"101 Stray Dogs\"",
    "28": "Hell Sign \"Bursting Grudge\"",
    "29": "Hell Sign \"Double Stripe\"",
    "30": "Moon Dream \"Eclipse Nightmare\"",
    "32": "Orb Sign \"Impregnable Fortress' Yin-Yang Orbs\"",
    "33": "Orb Sign \"Hard-to-Photograph Shotgun Coronation of the Gods\"",
    "34": "Dream Heron \"One-Winged Dream Heron\"",
    "36": "Bamboo Sign \"Bamboo Labyrinth\"",
    "37": "Myōga Ginger \"Mesmerism Dance\"",
    "38": "Broadleaf Sign \"Tanabata Star Dream\"",
    "39": "Myōga Blessing \"Behind Nightmare\"",
    "41": "Otherworld \"Distorted Fire\"",
    "42": "Otherworld \"Resentful Rain of Hell\"",
    "43": "Moon \"Cosmic Radiation\"",
    "44": "Otherworld \"Ōmagatoki -Dream-\"",
    "45": "\"The Moon is Falling!\"",
    "47": "\"Trembling, Shivering Nightmare\"",
    "48": "\"Psychedelic Mandala\"",
    "49": "\"Pure Light with Extreme Majesty\"",
    "50": "\"Danmaku for Killing with Certainty via Nightmares\"",
    "51": "Secret Ceremony \"Matarah Sukkha\"",
    "52": "Secret Ceremony \"The Rear Face's Wicked Flames\"",
    "53": "Back Sign \"Halo of the Absolute Secret God\"",
    "54": "Secret Ceremony \"Secret God's Behind-the-Scenes Danmaku\"",
    "55": "Secret Ceremony \"Arcane Dupion\"",
    "57": "Scarlet Devil Sign \"Bloody Catastrophe\"",
    "61": "Divine Scarlet Sign \"Bloody Laser of Seventeen Articles\"",
    "62": "Scarlet Star Sign \"Superhuman Catastrophe Pilgrimage\"",
    "64": "Wind God Sign \"Mishabashira\"",
    "66": "Wind Flower Sign \"Mishaguji-sama's Right and Wrong\"",
    "68": "Wind Flower Sign \"Onbashira Trial\"",
    "72": "Shining Night Sign \"Big Bullet Branch of Hourai\"",
    "70": "Scarlet Needle Sign \"Keystones Grow Bigger, Too!\"",
    "69": "Eternal Night Sign \"Bullet Branch of Hourai in a Pot\"",
    "74": "Scarlet Night Sign \"Bullet Keystones of Hourai\"",
    "75": "Earth Spirit Sign \"Mind Stellar Steal\"",
    "76": "Earth Mystic Sign \"Shikigami of the Id\"",
    "77": "\"Perfect Mind Control\"",
    "78": "Earth Mystic Sign \"Shikigami's Giant Star\"",
    "80": "Earth Spirit Sign \"Mind Stellar Relief\"",
    "81": "Divine Star Sign \"Unidentified Ghost-Light Crowd\"",
    "82": "Shining Heaven Sign \"Thunderclap Dondoko Drum\"",
    "83": "Shining Divine Sign \"Mysterious Dondoko Crowd\"",
    "84": "Scarlet Star Sign \"Unidentified Lightning Strike\"",
    "85": "Divine Scarlet Sign \"Stalker in a Thunderstorm\"",
    "86": "Shining Star Sign \"Unidentified Dondoko Drum\"",
    "87": "Gathering Night Sign \"Precious Life Scatters like Mist\"",
    "88": "Ultramarine Orb Sign \"Pure and Impure Danmaku\"",
    "91": "Gathering Orb Sign \"Mist Ray\"",
    "92": "Eternal Orb Sign \"An Unsullied Orb and a Much-Sullied Spirit\"",
    "93": "\"Secret God Barrier\"",
    "96": "\"Shoot the Danmaku Barrier!\"",
    "94": "\"Sneak-Photographer Exorcism Master Spark\"",
    "99": "\"The Nightmare One Has on Their Final Sunday\"",
    "100": "Paper Sign \"Zener Card Shuriken\"",
    "101": "Paper Sign \"Barrier-Enclosed Zener Card Shuriken\"",
    "58": "Star Divine Sign \"Superhuman of Seventeen Articles\"",
    "59": "Scarlet Star Sign \"Superhuman's Bloody Knife\"",
    "60": "Scarlet Divine Sign \"Catastrophe of Seventeen Articles\"",
    "63": "Mystic Flower Sign \"Butterfly Storm Yama Scepter\"",
    "65": "Wind Mystic Sign \"Dead Butterfly Onbashira\"",
    "67": "Mystic Wind Sign \"Native Butterfly Storm\"",
    "71": "Eternal Scarlet Sign \"Plummeting Bhava-agra in a Pot\"",
    "73": "Eternal Shining Sign \"Pot Growing Bigger\"",
    "79": "Earth Mystic Sign \"Shikigami of the Ego\"",
    "89": "Gathering Orb Sign \"Purely Beyond All in the Fog\"",
    "90": "Eternal Orb Sign \"Reckless Sacrifice's Reflection\"",
    "95": "\"Sneak-Photographer Exorcism from the Back\"",
    "97": "\"Coward's Master Spark\"",
    "98": "\"Unauthorized Danmaku Photography is Strictly Prohibited\""
}