{
    "2": "Fall Sign \"Heavy Tree Shaker\"",
    "3": "Fruit Sign \"Great Abundant Harvest\"",
    "4": "Wilted Path \"Forgotten Path of Leaves\"",
    "5": "Baked Sweet Potato \"Potato Shower Feast\"",
    "12": "Jealousy \"Heart Explosion\"",
    "13": "Cursed Field \"River of Youth\"",
    "14": "Resentment Art \"Pure Jealousy\"",
    "15": "Calamity \"Forbidden Cursed Zone\"",
    "21": "Umbrella Sign \"Suprise Explosion Attack\"",
    "22": "Well Bucket \"Inescapable Well\"",
    "23": "Small Thread \"Sticky Capture Rope\"",
    "24": "Rainbow Sign \"Broken Double Rainbow\"",
    "25": "Well Bucket \"Heavy Gas\"",
    "26": "Poison Sign \"Hidden Spider's Nest\"",
    "27": "Umbrella Sign \"Light Rain\"",
    "32": "Water Sign \"Kappa Waterfall\"",
    "33": "Dog Sign \"The Beast's Jaw\"",
    "34": "River Sign \"Splitting Sea\"",
    "35": "Mountain Nomad \"Expansion Trick\"",
    "36": "Kappa \"Shirikodama Swirl\"",
    "42": "Fist \"Fierce Sky Hook\"",
    "43": "Anchor Sign \"Lost Anchor of the Sea\"",
    "44": "Lightning \"Thunderstorm Nyuudou\"",
    "45": "Flood \"Floodgate Flash\"",
    "46": "Iron Fist \"Nyuudou Hammerhead Strike\"",
    "47": "\"Glimmering Depths\"",
    "52": "Light Oni \"Great Helix Praise\"",
    "53": "Oni Sign \"Miniature Oni-Rampage\"",
    "54": "Oni Sign \"Forgotten Oni Shackles\"",
    "55": "Hell \"Drunken Breath Shambles\"",
    "56": "Oni's Voice \"Big Bang Yell\"",
    "57": "Oni Sign \"Immaterial and Missing Power\"",
    "62": "Tiger Sign \"Savannah Chaser\"",
    "63": "Rod Sign \"Dowser Rod - Special\"",
    "64": "Heaven Sign \"Broken Treasure Map\"",
    "65": "Treasure \"Amanojaku Gold Rush\"",
    "66": "Treasure Sign \"Golden Treasure Land\"",
    "71": "Fusion \"Plasma Melter\"",
    "72": "Death Sign \"Midnight Zombie Rush\"",
    "73": "Giant Star \"Traveling Star\"",
    "74": "\"Corpse Party - Special Edition\"",
    "75": "Star Sign \"Starsign Collapse\"",
    "76": "Drunkard's Walk \"Cat Firework Festival\"",
    "77": "Seven Stars \"Grand Star Carrier\"",
    "81": "Heart Sign \"Love Overload\"",
    "82": "Brain Sign \"Brain Rupture\"",
    "83": "Memory \"DNA RNA Difference\"",
    "84": "Heart Flower \"Non-Photogenic Satori\"",
    "85": "\"Embryo's Nightmare\"",
    "86": "Recollection \"Nightmare Recollection of Kinkaku-ji\"",
    "87": "\"Thorn Garden\"",
    "90": "Temperament \"Heaven Train\"",
    "91": "Thunder Sign \"Catfish Storm\"",
    "92": "Earthquake \"Out of Order Escape Route\"",
    "93": "Orb Sign \"Star of Great Mythology\"",
    "94": "Keystone \"Pipe Filling Dance\"",
    "95": "Dragon Palace \"Flounder Dance of Dreams\"",
    "96": "\"Scarlet Weather Rhapsody\"",
    "97": "Dragon Fish \"Sky-Swimming Oarfish\"",
    "101": "Divine Sakura \"Full-Spring Petal Dance\"",
    "102": "Snake Sign \"Slithering Serpent\"",
    "103": "Hime River \"Flowing Green Jade River\"",
    "104": "Divine Pillar \"Great Meteor Impact\"",
    "105": "Iron Ring \"Moriya Ring Contest\"",
    "106": "Fleeting Path \"Crossing River Path\"",
    "107": "Native God \"Mishaguji-sama Revenge Plot\"",
    "111": "Unidentified \"Mirror of Truth\"",
    "112": "\"Protector Hijiri\"",
    "113": "Unidentified \"Red Pill, Blue Pill\"",
    "114": "Syncretism \"Manifestation of Makai Power\"",
    "115": "Unidentified \"Hanako Toilet Assault\"",
    "116": "\"Hidden Knife in Card Game\"",
    "117": "\"Space Station of a Certain Play\"",
    "120": "Talisman \"Dream Rebellion Newspaper\"",
    "121": "Star Sign \"Background Radiation\"",
    "122": "Miracle \"Divine Bumper Rain\"",
    "123": "Barrier \"Shattered Dream Border\"",
    "124": "Celestial Apparatus \"Big Bang Conspiracy\"",
    "125": "Frog Sign \"Wily Toad and Weakest Frog\"",
    "126": "Dream Sign \"Dream Barrier Shatter\"",
    "127": "Comet \"Master Spark - Speed Style\"",
    "128": "Youkai Extermination \"Ultimate Youkai Newspaper Burner\"",
    "131": "Reporting \"Hatate Himekaidou's Spoiler Stop\"",
    "132": "Continuous Shooting \"Panorama Picture\"",
    "133": "Far-sightedness \"Tengu Psychography Trick\"",
    "135": "Reporting \"Aya Shameimaru's Perfect Camera\"",
    "136": "Telescoping \"Stamp-Sized Picture\"",
    "137": "Snapshot \"Fast Shot Reporter\"",
    "138": "\"Dream Dweller Speed - Aya Shameimaru\""
}