{
    "0": "Frost Sign \"Deep Winter\"",
    "1": "Frost Sign \"Deep Winter -Lunatic-\"",
    "2": "Cold Sign \"Snowy Avanalance -Easy-\"",
    "3": "Cold Sign \"Snowy Avanalance\"",
    "4": "Cold Sign \"Snowy Avanalance -Hard-\"",
    "5": "Cold Sign \"Snowy Avanalance -Lunatic-\"",
    "6": "Winter Sign \"Freezing Nature -Easy-\"",
    "7": "Winter Sign \"Freezing Nature\"",
    "8": "White Sign \"Freeze Ray\"",
    "9": "Mystic Sign \"Mastermind's Mind\"",
    "10": "Hermit Sign \"Phoenix's Egg -Easy-\"",
    "11": "Hermit Sign \"Phoenix's Egg\"",
    "12": "Hermit Sign \"Phoenix's Spread Wings\"",
    "13": "Hermit Sign \"Phoenix's Spread Wings -Lunatic-\"",
    "14": "Shikigami Sign \"Soaring Feline -Easy-\"",
    "15": "Shikigami Sign \"Soaring Feline\"",
    "16": "Yin Yang \"The Good Of The Cat\"",
    "17": "Yin Yang \"The Bad Of The Cat\"",
    "18": "Heaven Sign \"Tianxian's Earthquake -Easy-\"",
    "19": "Heaven Sign \"Tianxian's Earthquake\"",
    "20": "Flight Sign \"Soaring Olympics\"",
    "21": "Servant Sign \"Gouhou-Tendou's Dance of Protection\"",
    "22": "Hermit Sign \"Hourai's Immortality -Easy-\"",
    "23": "Hermit Sign \"Hourai's Immortality\"",
    "24": "Oni Sign \"Kimon Konjin's Many Directions\"",
    "25": "Direction Sign \"Kimontonkou's Endless War\"",
    "26": "Puppeteer Sign \"Maiden's Bunraku Performance\"",
    "27": "Puppeteer Sign \"Maiden's Bunraku Performance -Lunatic-\"",
    "28": "Blue Sign \"Fraternal Paris Dolls -Easy-\"",
    "29": "Blue Sign \"Fraternal Paris Dolls\"",
    "30": "Blue Sign \"Fraternal Paris Dolls -Hard-\"",
    "31": "Blue Sign \"Fraternal Dolls Of Napoleon\"",
    "32": "Scarlet Sign \"Fire-Red Dutch Dolls -Easy-\"",
    "33": "Scarlet Sign \"Fire-Red Dutch Dolls\"",
    "34": "White Sign \"Snow-White Russian Dolls\"",
    "35": "White Sign \"Snow-White Russian Dolls -Lunatic-\"",
    "36": "Darkness Sign \"Murderous London Dolls -Easy-\"",
    "37": "Darkness Sign \"Murderous London Dolls\"",
    "38": "Cycle Sign \"Resurrected Tibetan Dolls\"",
    "39": "Elegant Sign \"Beautiful Kyoto Dolls\"",
    "40": "Malediction \"Ghostly Shanghai Dolls -Easy-\"",
    "41": "Malediction \"Ghostly Shanghai Dolls\"",
    "42": "Malediction \"Ghostly Shanghai Dolls -Hard-\"",
    "43": "Malediction \"Hourai Elixir\"",
    "44": "Noisy Sign \"Phantom's Stunning Performance -Easy-\"",
    "45": "Noisy Sign \"Phantom's Stunning Performance\"",
    "46": "Noisy Sign \"Live Poltergeist Performance\"",
    "47": "Noisy Sign \"Live Poltergeist Performance -Lunatic-\"",
    "48": "String Performance \"Giuseppe Guarneri's finest Violins -Easy-\"",
    "49": "String Performance \"Giuseppe Guarneri's finest Violins\"",
    "50": "Divine Strings \"Antonio Stradivari's perfect Violins\"",
    "51": "Fake Strings \"Antonio Stradivari's Spirit\"",
    "52": "Trumpet Spirit \"Terumasa Hino's Jazz Performance -Easy-\"",
    "53": "Trumpet Spirit \"Terumasa Hino's Jazz Performance\"",
    "54": "Nether Trumpet \"Clifford Brown's Spirit\"",
    "55": "Nether Trumpet \"Clifford Brown's Spirit -Lunatic-\"",
    "56": "Nether Keys \"Paolo Fazioli's Dark Keys -Easy-\"",
    "57": "Nether Keys \"Paolo Fazioli's Dark Keys\"",
    "58": "Key Spirit \"Ignaz Bösendorfer's Piano Keys\"",
    "59": "Key Spirit \"Ignaz Bösendorfer's Piano Keys -Lunatic-\"",
    "60": "Funeral Concert \"Prismriver's Concerto -Easy-\"",
    "61": "Funeral Concert \"Prismriver's Concerto\"",
    "62": "Noisy Funeral \"A Song For River Styx\"",
    "63": "Noisy Funeral \"A Song For River Styx -Lunatic-\"",
    "64": "Great Funeral Concert \"Prismriver's Concerto Grosso -Easy-\"",
    "65": "Great Funeral Concert \"Prismriver's Concerto Grosso\"",
    "66": "Great Funeral Concert \"Prismriver's Concerto Grosso: Revised\"",
    "67": "Great Funeral Concert \"Prismriver's Concerto Grosso: Wondrous\"",
    "68": "Ghost Sword \"Slicing of Dinner -Easy-\"",
    "69": "Ghost Sword \"Slicing of Dinner\"",
    "70": "Preta Sword \"World of Desires\"",
    "71": "Hungry King Sword \"Resurrection of the Preta\"",
    "72": "Hell Realm Sword \"One Million Yojana in One Slash -Easy-\"",
    "73": "Hell Realm Sword \"One Million Yojana in One Slash\"",
    "74": "Hell Fire Sword \"Slicing the Fires of Hell\"",
    "75": "Hell God Sword \"Kusanagi's Famous Journey\"",
    "76": "Animal Realm Sword \"The Curse Of The Lazy -Easy-\"",
    "77": "Animal Realm Sword \"The Curse Of The Lazy\"",
    "78": "Asura Sword \"Obsession with your Jealousy\"",
    "79": "Asura Sword \"Obsession with your Jealousy -Lunatic-\"",
    "80": "Human Realm Sword \"Enlightenment Of Desires -Easy-\"",
    "81": "Human Realm Sword \"Enlightenment Of Desires\"",
    "82": "Human Era Sword \"The Truth of Ten Desires\"",
    "83": "Human God Sword \"Conventions of the Ultimate Truth\"",
    "84": "Heaven Sword \"Five Signs of the Proud Deva -Easy-\"",
    "85": "Heaven Sword \"Five Signs of the Proud Deva\"",
    "86": "Deva Realm Sword \"Truths of the Soul\"",
    "87": "Heaven God Sword \"Soul of the Deva\"",
    "88": "Six Realms Sword \"Erasure of Bad Thoughts -Easy-\"",
    "89": "Six Realms Sword \"Erasure of Bad Thoughts\"",
    "90": "Six Realms Sword \"Erasure of Bad Thoughts -Hard-\"",
    "91": "Six Realms Sword \"Erasure of Bad Thoughts -Lunatic-\"",
    "92": "Losing Hometown \"Village of Self-Loss -Lost Soul-\"",
    "93": "Losing Hometown \"Village of Self-Loss -Haunting Sins-\"",
    "94": "Losing Hometown \"Village of Self-Loss -End of Paths-\"",
    "95": "Losing Hometown \"Village of Self-Loss -End of Life-\"",
    "96": "Deadly Dance \"Law of Mortality -Misunderstood-\"",
    "97": "Deadly Dance \"Law of Mortality -Insects Death-\"",
    "98": "Deadly Dance \"Law of Mortality -Deadly Sting-\"",
    "99": "Deadly Dance \"Law of Mortality -Death's Hell-\"",
    "100": "Flowery Soul \"Butterfly Swarm\"",
    "101": "Flowery Soul \"Swallowtail Swarm\"",
    "102": "Flowery Soul \"Butterflys Nest\"",
    "103": "Flowery Soul \"Poisonous Butterfly\"",
    "104": "Subtle Melody \"Repository of Hirokawa -Faked Death-\"",
    "105": "Subtle Melody \"Repository of Hirokawa -Haunting Ghost-\"",
    "106": "Subtle Melody \"Repository of Hirokawa -Deadly Spirit-\"",
    "107": "Subtle Melody \"Repository of Hirokawa -Godly Spirit-\"",
    "108": "Cherry Blossom Sign \"Perfect Ink-Black Cherry Blossom -Lock-\"",
    "109": "Cherry Blossom Sign \"Perfect Ink-Black Cherry Blossom -Lost Mind-\"",
    "110": "Cherry Blossom Sign \"Perfect Ink-Black Cherry Blossom -Eternal Sleep-\"",
    "111": "Cherry Blossom Sign \"Perfect Ink-Black Cherry Blossom -Blossom-\"",
    "112": "\"Yuyuko's Resurrection -30%% Reflowering-\"",
    "113": "\"Yuyuko's Resurrection -50%% Reflowering-\"",
    "114": "\"Yuyuko's Resurrection -80%% Reflowering-\"",
    "115": "\"Yuyuko's Resurrection -100%% Reflowering-\"",
    "116": "Oni Sign \"Colorful Oni Dance\"",
    "117": "Kishin \"Soaring Cat of Luck\"",
    "118": "Shikigami \"Heavenly Fox Barrier\"",
    "119": "Shikigami \"Banquet of Abe no Seimei\"",
    "120": "Shiki Brilliance \"A Laser of Many Tricks\"",
    "121": "Shiki Brilliance \"Enclosing Siege from Everywhere\"",
    "122": "Shiki Brilliance \"Princess Tenko -Fading-\"",
    "123": "Shiki Shot \"Ultimate Buddhist Chainsaw\"",
    "124": "Shiki Shot \"Curving Knives of Woe\"",
    "125": "Shikigami Summoning \"Chen's Assault\"",
    "126": "\"Kokkuri-san's Trials\"",
    "127": "Illusion God \"Dream of Fox's Past\"",
    "128": "Shikigami \"Oni's Vessels\"",
    "129": "Shikigami \"White Fox Dashing through the Night\"",
    "130": "Barrier \"Blessing of Dreams and Wishes\"",
    "131": "Barrier \"Imbalance of Movement and Stillness\"",
    "132": "Barrier \"Room of Light and Shadow\"",
    "133": "Evil Spirits \"Xanadu of Entrapment and Freedom\"",
    "134": "Evil Spirits \"Yukari Yakumo's Eternal Journey\"",
    "135": "Evil Spirits \"Bewitching Butterfly Living in Hakugyokorou\"",
    "136": "Sinister Spirits \"Butterflies of Ghostly Friend\"",
    "137": "Shikigami \"Ran Yakumo's Wicked Assault\"",
    "138": "\"Fading Line between Humans and Youkai\"",
    "139": "Barrier \"Boundary of Death and Existance\"",
    "140": "\"Boundary between Dream and Nightmare\""
}