{
    "0": "Horror \"Well-Hidden Murder\"",
    "2": "Trap Sign \"Small Fry's Doom\"",
    "4": "Spider \"Webbed Queen's Nest\"",
    "6": "Miasma Sign \"Deadly Poison\"",
    "8": "Miasma \"Down With Sickness\"",
    "10": "Jealousy Sign \"Jealous Beast\"",
    "12": "Envy \"Invisible Monster Creeping Up\"",
    "14": "Grandpa Hanasaka \"Forgotten Flower of the Past\"",
    "16": "Grandpa Hanasaka \"Rising Ashes of a Burnt Flower\"",
    "18": "Tongue-Cut Sparrow \"The Fearsome Mrs. Cutter\"",
    "20": "Tongue-Cut Sparrow \"Demon Under Moonlight\"",
    "22": "Malice Sign \"The Hidden Shrine of the Moon\"",
    "24": "Malice Sign \"Eternal Visit to Hidden Shrine\"",
    "26": "Oni Sign \"Staggering Rampo\"",
    "30": "Mysterious Ring \"Hell's Eternal Handcuffs\"",
    "32": "Shackles Sign \"Burnmark of Eternity\"",
    "34": "Feat of Strength \"Landslide on Mt. Ooe\"",
    "36": "Feat of Strength \"Earthquake Shattering Mr. Ooe\"",
    "38": "Big Four Arcanum \"Fierce God's Firecrackers\"",
    "40": "Big Four Arcanum \"Fierce God's Firecrackers\"",
    "42": "Recollection \"Terrible Souvenir\"",
    "44": "Recollection \"Terrifying Hypnotism\"",
    "46": "Recollection \"Double Black Death Butterfly\"",
    "50": "Recollection \"Flying Insect's Nest\"",
    "54": "Recollection \"Border of Wave & Particle\"",
    "58": "Recollection \"Mt. Togakushi Toss\"",
    "62": "Recollection \"Night Parade of a Million Demons\"",
    "66": "Recollection \"Deep Fog Labyrinth\"",
    "70": "Recollection \"Wind God's Leaf-Veiling\"",
    "74": "Recollection \"Tengu's Macroburst\"",
    "78": "Recollection \"Torii Whorl-Wind\"",
    "82": "Recollection \"Spring Kyoto Dolls\"",
    "86": "Recollection \"Straw Doll Kamikaze\"",
    "90": "Recollection \"Return Inanimateness\"",
    "94": "Recollection \"Mercury Poison\"",
    "98": "Recollection \"Princess Undine\"",
    "102": "Recollection \"Philosopher's Stone\"",
    "106": "Recollection \"Extending Arm\"",
    "110": "Recollection \"Kappa's Pororoca\"",
    "114": "Recollection \"Trauma in the Glimmering Depths\"",
    "118": "Cat Sign \"Cat's Walk\"",
    "120": "Cat Sign \"Vengeful Cat Spirit's Erratic Step\"",
    "122": "Cursed Sprite \"Zombie Fairy\"",
    "124": "Cursed Sprite \"Vengeful Spirit: Possessed Fairy\"",
    "126": "Malicious Spirit \"Spleen Eater\"",
    "128": "Corpse Spirit \"Vengeful Cannibal Spirit\"",
    "130": "Atonement \"Needle Mountain of a Former Hell\"",
    "132": "Atonement \"The Needles of Yore & the Vengeful Spirits in Pain\"",
    "134": "\"Rekindling of Dead Ashes\"",
    "136": "\"Small Demon's Revival\"",
    "138": "Youkai \"Blazing Wheel\"",
    "142": "Atomic Fire \"Nuclear Fusion\"",
    "144": "Atomic Fire \"Nuclear Excursion\"",
    "145": "Atomic Fire \"Uncontainable Nuclear Reaction\"",
    "146": "Explosion Sign \"Petit Flare\"",
    "147": "Explosion Sign \"Mega Flare\"",
    "148": "Explosion Sign \"Giga Flare\"",
    "149": "Explosion Sign \"Peta Flare\"",
    "150": "Blazing Star \"Fixed Star\"",
    "152": "Blazing Star \"Planetary Revolution\"",
    "153": "Blazing Star \"Ten Evil Stars\"",
    "154": "\"Hell & Heaven Meltdown\"",
    "156": "\"Hell's Tokamak\"",
    "158": "\"Hell's Artificial Sun\"",
    "160": "\"Subterranean Sun\"",
    "162": "Esoterica \"Nine Syllable Stabs\"",
    "163": "Miracle \"Miracle Fruit\"",
    "164": "Divine Virtue \"Bumper Crop Rice Shower\"",
    "165": "Image \"All Ancestors Standing Beside Your Bed\"",
    "166": "Image \"Danmaku Paranoia\"",
    "167": "Instinct \"Release of the Id\"",
    "168": "Suppression \"Super-Ego\"",
    "169": "Response \"Youkai Polygraph\"",
    "170": "Unconscious \"Rorschach in Danmaku\"",
    "171": "Rekindled \"The Embers of Love\"",
    "172": "Depths \"Genetics of the Unconscious\"",
    "173": "\"Philosophy of a Hated Person\"",
    "174": "\"Subterranean Rose\""
}