{
    "0": "Horror \"Well-Hidden Murder\"",
    "2": "Trap Sign \"Small Fry's Doom\"",
    "4": "Spider \"Webbed Queen's Nest\"",
    "6": "Miasma Sign \"Deadly Poison\"",
    "8": "Miasma \"Down With Sickness\"",
    "10": "Jealousy Sign \"Jealous Beast\"",
    "12": "Envy \"Invisible Monster Creeping Up\"",
    "14": "Grandpa Hanasaka \"Forgotten Flower of the Past\"",
    "16": "Grandpa Hanasaka \"Rising Ashes of a Burnt Flower\"",
    "18": "Tongue-Cut Sparrow \"The Fearsome Mrs. Cutter\"",
    "20": "Tongue-Cut Sparrow \"Demon Under Moonlight\"",
    "22": "Malice Sign \"The Hidden Shrine of the Moon\"",
    "24": "Malice Sign \"Eternal Visit to Hidden Shrine\"",
    "26": "Oni Sign \"Staggering Rampo\"",
    "30": "Mysterious Ring \"Hell's Eternal Handcuffs\"",
    "32": "Shackles Sign \"Burnmark of Eternity\"",
    "34": "Feat of Strength \"Landslide on Mt. Ooe\"",
    "36": "Feat of Strength \"Earthquake Shattering Mr. Ooe\"",
    "38": "Big Four Arcanum \"Fierce God's Firecrackers\"",
    "40": "Big Four Arcanum \"Fierce God's Firecrackers\"",
    "42": "Recollection \"Mental Trauma\"",
    "44": "Recollection \"Endless Nightmare Land\"",
    "46": "Recollection \"Nightmare Double Black Death Butterfly\"",
    "50": "Recollection \"Nightmare Flying Insect's Nest\"",
    "54": "Recollection \"Nightmare Border of Wave & Particle\"",
    "58": "Recollection \"Nightmare Mt. Togakushi Toss\"",
    "62": "Recollection \"Nightmare Parade of a Million Demons\"",
    "66": "Recollection \"Nightmare Deep Fog Labyrinth\"",
    "70": "Recollection \"Nightmare Wind God's Leaf-Veiling\"",
    "74": "Recollection \"Nightmare Tengu's Macroburst\"",
    "78": "Recollection \"Nightmare Torii Whorl-Wind\"",
    "82": "Recollection \"Nightmare Spring Kyoto Dolls\"",
    "86": "Recollection \"Nightmare Straw Doll Kamikaze\"",
    "90": "Recollection \"Nightmare Return Inanimateness\"",
    "94": "Recollection \"Nightmare Mercury Poison\"",
    "98": "Recollection \"Nightmare Princess Undine\"",
    "102": "Recollection \"Nightmare Philosopher's Stone\"",
    "106": "Recollection \"Nightmare Extending Arm\"",
    "110": "Recollection \"Nightmare Kappa's Pororoca\"",
    "114": "Recollection \"Nightmare Trauma in the Glimmering Depths\"",
    "118": "Cat Sign \"Scared Cat at Night\"",
    "120": "Cat Sign \"Drunken Cat's Cursed Stroll\"",
    "122": "Cursed Sprite \"Graveyard Shift\"",
    "124": "Cursed Sprite \"Graveyard Shift: Zombie Apocalypse\"",
    "126": "Malicious Spirit \"Spiral of Death\"",
    "128": "Corpse Spirit \"Monster Chomp\"",
    "130": "Atonement \"Needle Mountain in a Haystack\"",
    "132": "Atonement \"Pain and Suffering of Vengeful Spirits\"",
    "134": "\"Corpse Party\"",
    "136": "\"Corpse Party: Final Reprise\"",
    "138": "Youkai \"Broken Wheel on Fire\"",
    "142": "Atomic Fire \"Solar Eruption\"",
    "144": "Atomic Fire \"Solar Blaze\"",
    "145": "Atomic Fire \"Quazar Reaction\"",
    "146": "Explosion Sign \"Ultra Flare\"",
    "147": "Explosion Sign \"Hyper Flare\"",
    "148": "Explosion Sign \"Mega Flare\"",
    "149": "Explosion Sign \"Extra Flare\"",
    "150": "Blazing Star \"Broken Constellation\"",
    "152": "Blazing Star \"Gravitational Rift\"",
    "153": "Blazing Star \"Ten Stars of Evil Desires\"",
    "154": "\"Refiring of Hell Energy\"",
    "156": "\"Hell's New Reactor\"",
    "158": "\"Hell's Artificial Black Hole\"",
    "160": "\"Subterranean Black Hole\"",
    "162": "Trauma \"Mental Cage\"",
    "163": "Heartbeat \"Heart Chamber Rupture\"",
    "164": "Breaking Point \"Cry Leading to Sleep\"",
    "165": "Closure Sign \"Standing Alone in the Dream Realm\"",
    "166": "Prohibiting Vision \"Optical Blind\"",
    "167": "Non-stop \"Daruma-san Won't Fall Down\"",
    "168": "Forbidden Life \"A Child is Born with a Red Face\"",
    "169": "Forbidden Area \"No Entry\"",
    "170": "Forbidden Love \"A Tragedy Lead by Fate\"",
    "171": "Forbidden Poem \"A Red Bug Told Me\"",
    "172": "Flow Sign \"Kappa's Dream Flow\"",
    "173": "\"Hated Red Kappa\"",
    "174": "\"A Kappa Who Dreams Of Life\""
}