{
    "0": "Avalance Sign \"Dangerous Ski-Accident\"",
    "1": "Cold Wind \"Freezing Air\"",
    "2": "Snowball Sign \"Growing Effects\"",
    "10": "Magic Sign \"Stardust\"",
    "11": "Magic Sign \"Stardust Reverie\"",
    "12": "Magic Sign \"Illusion Star\"",
    "20": "Time Sign \"Private Vision\"",
    "22": "Time Sign \"Mysterious Jack\"",
    "30": "Hesitation Sign \"Sword of Binding Desires\"",
    "32": "Hesitation Sign \"Half Body Disillusion\"",
    "40": "Wave Sign \"Lunar Surface Ripple (Luna Wave)\"",
    "42": "Scatter Sign \"Dream of Prosperity (Luna Megalopolis)\"",
    "50": "Freeze Sign \"Perfect Freeze\"",
    "52": "Freeze Sign \"Cold Divinity\"",
    "60": "Noise Sign \"Soul Noise Flow\"",
    "62": "Noise Sign \"Lyrica Solo Live\"",
    "70": "Bird Sign \"Human Cage\"",
    "71": "Bird Sign \"Human Cage Double\"",
    "72": "Bird Sign \"Mysterious Song\"",
    "80": "Rabbit Sign \"Great Fortune Crest\"",
    "82": "Rabbit Sign \"Bare White Rabbit of Inaba\"",
    "90": "Flower Sign \"Blossoming of Gensokyo\"",
    "92": "Fantasy \"The Beauties of Nature\"",
    "100": "Wind Sign \"Wind God's Fan\"",
    "102": "Gust \"Wind God Girl\"",
    "110": "Poison Sign \"Nerve Poison\"",
    "112": "Poison Sign \"A Poison for Melancholy\"",
    "120": "Thrown Coins \"Yesterday's Money\"",
    "122": "Shinigami \"Higan Retour\"",
    "130": "Guilt Sign \"Wandering Sin\"",
    "132": "Judgement \"Last Judgement\"",
    "140": "Noise Sign \"Soul Go Happy\"",
    "142": "Noise Sign \"Merlin Happy Live\"",
    "150": "Noise Sign \"Noise Melancholy\"",
    "152": "Noise Sign \"Lunasa Solo Live\""
}