{
    "0": "Moon Sign \"Rain Spam\"",
    "4": "Moon Sign \"Moon Tornado\"",
    "8": "Shooting Star \"Comet Crasher\"",
    "12": "Stardust \"Broken Sprinkle\"",
    "16": "Star Sign \"Mold Breaker\"",
    "20": "Sunlight \"Solar Flare\"",
    "24": "Light Sign \"Gravity Field\"",
    "28": "Sunfire \"Shatter Trick\"",
    "32": "Sky Sign \"Firey Rain\"",
    "36": "Team Tech \"Crash Course\"",
    "40": "\"Rainbow Combination\"",
    "44": "Rainbow Light \"Prism Splitter\"",
    "48": "Light Fairy \"Unbroken Ring\"",
    "52": "Light Sign \"Great Flame Wall\"",
    "56": "Starlight \"Star Laser Breaker\"",
    "60": "Light Sign \"Triple Meteor Impact\"",
    "64": "Starfire \"Shatter Trick\"",
    "68": "Bright Star \"Galaxy Spin\"",
    "72": "Team Tech \"Crash Course\"",
    "76": "\"Rainbow Combination\"",
    "80": "Sun Sign \"Heatstroke\"",
    "84": "Sun Sign \"Sunburn\"",
    "88": "Shooting Star \"Comet Ring\"",
    "92": "Stardust \"Lost Control Star\"",
    "96": "Star Sign \"Trailing Tail Star\"",
    "100": "Moonlight \"Silent Room Light\"",
    "104": "Light Sign \"Suprising Sun\"",
    "108": "Moonfire \"Shatter Trick\"",
    "112": "Sky Sign \"Shard Breaker\"",
    "116": "Team Tech \"Crash Course\"",
    "120": "\"Rainbow Combination\"",
    "124": "Moonlight \"Creeper Darkness\"",
    "128": "Hindering Light \"Moonlight Barrier\"",
    "132": "Night Sign \"Night Adventure\"",
    "136": "Starlight \"Star Storm Omega\"",
    "140": "Light Sign \"Extensive Meteor Impact\"",
    "144": "Starfire \"Shatter Trick\"",
    "148": "Bright Star \"Great Triangle Spinner\"",
    "152": "Team Tech \"Crash Course\"",
    "156": "\"Rainbow Combination\"",
    "160": "Star Sign \"Space Rain\"",
    "164": "Star Sign \"Following Star\"",
    "168": "Flickering Light \"Blinding Flash\"",
    "172": "Light Fairy \"Reflector Light\"",
    "176": "Light Sign \"Mirror Bouncer\"",
    "180": "Moonlight \"Moon Flower\"",
    "184": "Light Sign \"Bright Moon\"",
    "188": "Moonfire \"Shatter Trick\"",
    "192": "Falling Light \"Combination Fire\"",
    "196": "Team Tech \"Crash Course\"",
    "200": "\"Rainbow Combination\"",
    "204": "Moonlight \"Moon Breaker\"",
    "208": "Light Barrier \"Escape Route\"",
    "212": "Moonlight \"Silent Tornado\"",
    "216": "Sunlight \"Piercing Sunlight\"",
    "220": "Light Sign \"Gravity Inflection\"",
    "224": "Sunfire \"Shatter Trick\"",
    "228": "Violent Light \"Three Suns\"",
    "232": "Team Tech \"Crash Course\"",
    "236": "\"Rainbow Combination\"",
    "240": "Light Sign \"Motivation Seeker\"",
    "241": "Light Blast \"Phantasmagoria Dream\"",
    "242": "Magic Bullet \"Light Yo-Yo\"",
    "243": "Closure Sign \"Artificial Solar System\"",
    "244": "Love Sign \"Low-Energy Master Spark\"",
    "245": "Unsealed Magic \"Birth of the Universe\"",
    "246": "Magic Cross \"Holy Magic Fire\"",
    "247": "Shooting Star \"Grand Impact\"",
    "248": "\"Master Spark - Speed Style\"",
    "249": "\"Fairy Killing Ray\""
}