{
    "0": "Moon Sign \"Lunar Laser\"",
    "1": "Night Sign \"Hawk Stalking its Prey\"",
    "2": "Darkness Sign \"Dark Stalker\"",
    "3": "Ice Sign \"Idiot-Proof Ice\"",
    "4": "Hail Sign \"Frostbite\"",
    "5": "\"Perfect Freeze\"",
    "6": "Snow Sign \"Snowball Effect\"",
    "7": "Flower Sign \"Poisonous Flower\"",
    "8": "Flower Sign \"Poison Hemlock\"",
    "9": "Rainbow Sign \"Rainbow Windmill\"",
    "10": "Illusion Sign \"Vines of the Jungle\"",
    "11": "Colorful Sign \"Colorful Torrent\"",
    "12": "Colorful Sign \"Beautiful Color-Dance\"",
    "13": "Colorful Sign \"Rainbow after Hurricane\"",
    "14": "Fire Sign \"Agni Inferno\"",
    "15": "Water Sign \"Queen Undine\"",
    "16": "Wood Sign \"Trees Shedding Leaves\"",
    "17": "Earth Sign \"Catastrophic Earthquake\"",
    "18": "Metal Sign \"Atom Splitting\"",
    "19": "Fire Sign \"Agni Inferno High Level\"",
    "20": "Wood Sign \"Trees Sheeding Leaves High Level\"",
    "21": "Earth Sign \"Catastrophic Earthquake High Level\"",
    "22": "Fire Sign \"Agni Reaction\"",
    "23": "Water Sign \"Drowning in the Ocean\"",
    "24": "Wood Sign \"Autumm Fall\"",
    "25": "Earth Sign \"Trilithon Earthquake\"",
    "26": "Metal Sign \"Golden Dragon\"",
    "27": "Fire & Earth Sign \"Volcano Eruption\"",
    "28": "Wood & Fire Sign \"Deforestation Fire\"",
    "29": "Water & Wood Sign \"Poison Elf\"",
    "30": "Metal & Water Sign \"Uranium Poison\"",
    "31": "Earth & Metal Sign \"Mining a Mountain\"",
    "32": "Conjuring \"Teleportation Trick\"",
    "33": "Conjuring \"High-Speed Teleport\"",
    "34": "Illusion Existence \"Frozen in Death\"",
    "35": "Illusion Image \"Clock that never Ticks\"",
    "36": "Maid Secret Skill \"Stabbed Doll\"",
    "37": "Illusion Phantom \"Clock of the Maid\"",
    "38": "Illusion World \"ZA WARUDO\"",
    "39": "Spirit of Famous Vampire \"Dio Brando\"",
    "40": "\"Eternal Servant of the Vampires\"",
    "41": "Heaven's Punishment \"Star of Dracula\"",
    "42": "Nether Sign \"Deep-Red Hell\"",
    "43": "Curse \"Resurrection of Count Dracula\"",
    "44": "Scarlet Sign \"Scarlet Blast\"",
    "45": "\"A Gensokyo dyed in Scarlet\"",
    "46": "God's Punishment \"Ruler of the Demons\"",
    "47": "Hell Sign \"Mountain of a Million Knives\"",
    "48": "Divine Art \"Vampire in a Mirror\"",
    "49": "Scarlet Sign \"Scarlet Lord\"",
    "50": "\"Gensokyo of the Vampires\"",
    "51": "Moon Sign \"Damp Rain on the Surface\"",
    "52": "Sun Sign \"Solar Flare\"",
    "53": "\"Librarian's Best Collection\"",
    "54": "Taboo \"Cranberry Prison\"",
    "55": "Taboo \"Lævateinn Slasher\"",
    "56": "Taboo \"Secret Duplication Art\"",
    "57": "Taboo \"Trap of the Moon\"",
    "58": "Taboo \"Maze of Hate\"",
    "59": "Forbidden Barrage \"Broken Wings\"",
    "60": "Forbidden Barrage \"Hide your Fears\"",
    "61": "Forbidden Barrage \"Clock that Ticks Away your Life\"",
    "62": "Secret Barrage \"And Then You Will Be Gone\"",
    "63": "Q.E.D. \"Ripples of Fallen Dreams\""
}