{
    "0": "Ghost Symbol \"Forgotten Demon Paradise\"",
    "2": "Ghost Symbol \"Forgotten Demon Paradise - Reincarnation -\"",
    "4": "Ghostly God \"Shrine Spirit\"",
    "6": "Ghostly God \"Shrine Spirit - Eternal Guard -\"",
    "8": "Hell Sign \"Hell's Breaking Point\"",
    "12": "Grand Demon Sign \"Vengeful Spirit - Mima -\"",
    "14": "Echo Sign \"Mountain Echo Reverb\"",
    "16": "Echo Sign \"Mountain Echo Voice Chamber\"",
    "18": "Echo Sign \"Power Yell Challenge\"",
    "22": "Mountain Echo \"Echo, Echo, Let it out!\"",
    "24": "Mountain Echo \"Grand Amplifier\"",
    "26": "Great Voice \"Rock Concert!\"",
    "28": "Great Voice \"Rock Concert Encore!\"",
    "30": "Rainbow Sign \"Suprise Umbrella Spinner\"",
    "32": "Recovery \"Natural Healing Factor\"",
    "36": "Poison Nail \"Poison Injector Claw\"",
    "38": "Poison Nail \"Poison Needle Claw\"",
    "40": "Desire Sign \"Natural Essence Summon Heal\"",
    "42": "Desire Spirit \"Scoring Point Item Value\"",
    "44": "Evil Sign \"Corpse Mangler\"",
    "45": "Evil Sign \"Ghostly Abandon\"",
    "47": "Demonify \"Vital Loss\"",
    "51": "Possession \"Flawed Corpse Possession\"",
    "53": "Spirit Link \"Yoshika Link\"",
    "55": "Taoist Sign \"Corpse Control Center\"",
    "59": "Thunder Arrow \"Odin's Thundercloud\"",
    "60": "Thunder Arrow \"Odin's Thundercloud\"",
    "61": "Thunder Arrow \"Odin's Rage\"",
    "62": "Heaven Sign \"Cloud Surfer\"",
    "64": "Heaven Sign \"Surfing on Clouds, Upwards to Heaven\"",
    "66": "Throwing Dishes \"De-stressing Cup Smasher\"",
    "70": "Blaze Sign \"Grand Heaven Fire\"",
    "72": "Blaze Sign \"Hell on Heaven\"",
    "74": "Saint Girl \"Mononobe Twirler\"",
    "78": "Honor \"Shining Rainbow Laser\"",
    "80": "Honor \"Double Rainbow Laser\"",
    "82": "Hermit Sign \"Nurturing Sunrays\"",
    "84": "Hermit Sign \"Nurturing Sunray Drought\"",
    "86": "Summon \"Royal Clan's Dance Floor\"",
    "90": "Secret Treasure \"Armillary Sphere of Gravity\"",
    "93": "Secret Treasure \"Grand Gravity Vortex\"",
    "94": "Light Sign \"Grand Emperor Cannon\"",
    "96": "Light Sign \"Flashbomb of New Emperor\"",
    "98": "Discernment \"Constitution of Nature\"",
    "100": "Divine Light \"Honor the Avoidance of Deforestation\"",
    "102": "\"Nature Protecting Essences\"",
    "104": "\"Essence of Nature\"",
    "106": "First Duel \"Evil Forest Burning Incident\"",
    "107": "Second Duel \"Animal Planet Escape\"",
    "108": "Third Duel \"Hunting Bullet Pet\"",
    "109": "Hermit Sign \"Little People Party\"",
    "110": "Hermit Sign \"Frenzied Dogfight\"",
    "111": "Hermit Sign \"Aerial Bird Fighter\"",
    "112": "Hermit Sign \"Anti-Freezer Frog Development\"",
    "113": "Hermit Sign \"Newfound Animal Kingdom\"",
    "114": "Hermit Sign \"Civilized Human Line\"",
    "115": "Hermit Sign \"Forgotten Wilderness\"",
    "116": "Hermit Travels \"Long Journey of the East\"",
    "117": "\"Oni-Kasen Illusion Battle\"",
    "118": "Oni Sign \"Grand Oni Festival\"",
    "119": "Space Sign \"Grand Gravity Theory\"",
    "120": "Mountain Echo \"Earth Shattering Echo\"",
    "121": "Poison Nail \"Hidden Murder Poison\"",
    "122": "Taoist Sign \"TAO Fetal Movement ~Evil~\"",
    "123": "Vengeful Spirit \"Zeus's Thunder\"",
    "124": "Saint Girl \"Grand Boat Rider\"",
    "125": "\"Natural Universe\"",
    "126": "\"Oni Lands\""
}