{
    "0": "Ghost Symbol \"Forgotten Demon Paradise\"",
    "2": "Ghost Symbol \"Forgotten Demon Paradise - Reincarnation -\"",
    "4": "Ghostly God \"Shrine Spirit\"",
    "6": "Ghostly God \"Shrine Spirit - Eternal Guard -\"",
    "8": "Hell Sign \"Hell's Breaking Point\"",
    "12": "Grand Demon Sign \"Vengeful Spirit - Mima -\"",
    "14": "Echo Sign \"Mountain Echo Reverb\"",
    "16": "Echo Sign \"Mountain Echo Voice Chamber\"",
    "18": "Echo Sign \"Power Yell Challenge\"",
    "22": "Mountain Echo \"Echo, Echo, Let it out!\"",
    "24": "Mountain Echo \"Grand Amplifier\"",
    "26": "Great Voice \"Rock Concert!\"",
    "28": "Great Voice \"Rock Concert Encore!\"",
    "30": "Rainbow Sign \"Suprise Umbrella Spinner\"",
    "32": "Recovery \"Natural Healing Factor\"",
    "36": "Poison Nail \"Poison Injector Claw\"",
    "38": "Poison Nail \"Poison Needle Claw\"",
    "40": "Desire Sign \"Natural Essence Summon Heal\"",
    "42": "Desire Spirit \"Scoring Point Item Value\"",
    "44": "Evil Sign \"Corpse Mangler\"",
    "45": "Evil Sign \"Ghostly Abandon\"",
    "47": "Demonify \"Vital Loss\"",
    "51": "Possession \"Flawed Corpse Possession\"",
    "53": "Spirit Link \"Yoshika Link\"",
    "55": "Taoist Sign \"Corpse Control Center\"",
    "59": "Thunder Arrow \"Odin's Thundercloud\"",
    "60": "Thunder Arrow \"Odin's Thundercloud\"",
    "61": "Thunder Arrow \"Odin's Rage\"",
    "62": "Heaven Sign \"Cloud Surfer\"",
    "64": "Heaven Sign \"Surfing on Clouds, Upwards to Heaven\"",
    "66": "Throwing Dishes \"De-stressing Cup Smasher\"",
    "70": "Blaze Sign \"Grand Heaven Fire\"",
    "72": "Blaze Sign \"Hell on Heaven\"",
    "74": "Saint Girl \"Mononobe Twirler\"",
    "78": "Honor \"Shining Rainbow Laser\"",
    "80": "Honor \"Double Rainbow Laser\"",
    "82": "Hermit Sign \"Nurturing Sunrays\"",
    "84": "Hermit Sign \"Nurturing Sunray Drought\"",
    "86": "Summon \"Royal Clan's Dance Floor\"",
    "90": "Secret Treasure \"Armillary Sphere of Gravity\"",
    "93": "Secret Treasure \"Grand Gravity Vortex\"",
    "94": "Light Sign \"Grand Emperor Cannon\"",
    "96": "Light Sign \"Flashbomb of New Emperor\"",
    "98": "Discernment \"Constitution of Nature\"",
    "100": "Divine Light \"Honor the Avoidance of Deforestation\"",
    "102": "\"Nature Protecting Essences\"",
    "104": "\"Essence of Nature\"",
    "106": "Unknown \"Will-o'-wisps in Unknown Orbit\"",
    "107": "Unknown \"Skyfish with Unknown Shape\"",
    "108": "Unknown \"Youkai Orb of Unknown Mechanics\"",
    "109": "First Duel \"Primate Danmaku Transformation\"",
    "110": "Second Duel \"Carnivorous Danmaku Transformation\"",
    "111": "Third Duel \"Avian Danmaku Transformation\"",
    "112": "Fourth Duel \"Amphibian Danmaku Transformation\"",
    "113": "Fifth Duel \"Scrolls of Frolicking Animals\"",
    "114": "Sixth Duel \"Tanuki's Monstrous School\"",
    "115": "Seventh Duel \"Wild Deserted Island\"",
    "116": "Transformation \"Pseudo-Exorcism of the Stupid Shrine Maiden\"",
    "117": "\"Mamizou Danmaku in Ten Transformations\"",
    "118": "Raccoon Sign \"Full Moon Pompokolin\"",
    "119": "Cherry Blossom Sign \"Cherry Blossom Blizzard Hell\"",
    "120": "Mountain Echo \"Yamabiko's Specialty Echo Demonstration\"",
    "121": "Poison Nail \"Undead Murderer\"",
    "122": "Taoist Sign \"TAO Fetal Movement ~Dao~\"",
    "123": "Vengeful Spirit \"Iruka's Thunder\"",
    "124": "Saint Girl \"Sun Goddess's Sacrifice\"",
    "125": "\"Divine Spirits' Universe\"",
    "126": "\"Wild Carpet\""
}