{
    "2": "Water Sign \"Giant Kraken Wonder\"",
    "3": "Ice Sign \"Ice Spike Biome\"",
    "4": "Tide Sign \"Hidden Waterfall Secret\"",
    "5": "Ice King \"Perfect Safespot Trickster\"",
    "6": "Fish Sign \"Rain comes Up, Rain comes Down\"",
    "7": "Scream \"Suffocating Yell\"",
    "8": "Flying Neck \"Spring-Trapped Neck Extension\"",
    "9": "Piercing Sound \"Surround-Sound Acoustics\"",
    "10": "Glinting Eyes \"Cerberus' Friends\"",
    "11": "Sutra \"Unlimited Wordlength\"",
    "12": "Flying Neck \"Flying Dragon Steed\"",
    "14": "Full Moon \"Inverted Moon Pain\"",
    "15": "\"20XX: The Year of Perfection\"",
    "16": "Regretful Life \"Eternal Offering-Grounds\"",
    "17": "Wolf Fang \"The Girl, and the Big Bad Wolf\"",
    "18": "Great Fire \"Unfrozen Flower Tale\"",
    "19": "\"Fire Bird -Illusion of Time-\"",
    "1": "\"Resurrection\"",
    "21": "Demonify \"Evil Zombie Master\"",
    "22": "Butterfly Sign \"Grave Riser\"",
    "23": "Poison Nail \"Murder Claw\"",
    "24": "Hermit Arts \"Claustrophobia Simulator\"",
    "25": "Cherry Blossom \"Grand Fan of Saigyouji\"",
    "26": "Hermit Arts \"Faster Than Lightspeed\"",
    "28": "Koto Sign \"Noise Explosion\"",
    "29": "Noise Sign \"Oh, Grand Bard, Sing For Me!\"",
    "30": "Thunder Sign \"Insane Drum Solo\"",
    "31": "Elegy \"Song of Death and Pain\"",
    "32": "Score \"Empty Singer\"",
    "33": "Taiko \"DJ-Remix\"",
    "34": "Double Chant \"Requiem for the Star God\"",
    "36": "Photography \"Fastest Dreamer Newspaper\"",
    "37": "Photography \"New Panorama App\"",
    "38": "Waterfall Sign \"Treasure or Bust\"",
    "39": "Fang Sign \"New Chewing-Toy\"",
    "40": "Waterfall Sign \"Rapid-Fire Watergun\"",
    "41": "Photography \"Spell-Design Critique\"",
    "42": "\"Dreamful Chronicles\"",
    "43": "Love Sign \"Explosion Spark\"",
    "44": "Time Sign \"Stopped Vampire Night\"",
    "45": "Light Sign \"Netherworld Ressurection Slash\"",
    "46": "Snake Sign \"Great Snake Game Time\"",
    "47": "Love Sign \"Gattling Gun Spark\"",
    "48": "Time Sign \"End is End\"",
    "49": "Higan Sword \"Wily Slash and Weakest Spirit\"",
    "50": "Snake Sign \"Fast Game of Snake\"",
    "52": "Mikuji \"Illegal Spell Breaker\"",
    "53": "\"A Bird in the Hand, Worth more than Nothing\"",
    "54": "\"Kamui Origins\"",
    "55": "\"Extermination Gohei Stab\"",
    "56": "\"Scum of Planet Earth\"",
    "57": "Shining Needle \"Killing Blow on Oni Island\"",
    "58": "Onbashira \"Greatest Onbashira\"",
    "59": "Green Stone \"Emerald Faker\"",
    "60": "Old Boat \"New Titanic Reveal\"",
    "61": "Oni Crowd \"Ogre Lord\"",
    "62": "\"Explosive God's Temper\"",
    "63": "Frog Sign \"Red Hourai Frog Death\"",
    "64": "Heat Dragon \"Firey Blood of Dragon\"",
    "65": "Oni Crowd \"Oni-Infested Meteor\"",
    "66": "\"Hijiri Laws of Pain\"",
    "67": "\"Stairway to Heaven, Right over here!\"",
    "68": "\"Sky of Scarlet, Ground of Blood\"",
    "69": "\"Impossible Nightmare\"",
    "70": "\"Danmaku of Powerplay\"",
    "71": "\"I wish for Heaven!\"",
    "72": "\"Information Blaster Bomb\"",
    "73": "\"Blocked Escarpment Path\"",
    "74": "\"Hey, Batter Batter!\"",
    "75": "\"Boundary of Finale and New Beginning\""
}