{
    "0": "Firefly Sign \"Meteor Impact\"",
    "1": "Firefly Sign \"Meteor of Extinction\"",
    "2": "Lamp Sign \"Moth Attraction\"",
    "3": "Lamp Sign \"Moth Attraction\"",
    "4": "Lamp Sign \"Moth Attraction\"",
    "5": "Lamp Sign \"Moth Attraction\"",
    "6": "Wriggle Sign \"Growing Bug\"",
    "7": "Wriggle Sign \"Growing Bug Storm\"",
    "8": "Wriggle Sign \"Nightmare Bug Storm\"",
    "9": "Wriggle Sign \"Nightbug Invasion\"",
    "10": "Hidden Bug \"Endless Sleep of Winter\"",
    "11": "Hidden Bug \"Endless Sleep of Winter\"",
    "12": "Hidden Bug \"Endless Sleep of Winter\"",
    "13": "Vocal Sign \"Yelling of the Night\"",
    "14": "Vocal Sign \"Yelling of the Night\"",
    "15": "Vocal Sign \"Yell of the Predator\"",
    "16": "Vocal Sign \"Yell of the Predator\"",
    "17": "Moth Sign \"Hawk Moth's Curse\"",
    "18": "Moth Sign \"Hawk Moth's Curse\"",
    "19": "Toxin Sign \"Poison of the Mind\"",
    "20": "Deadly Toxin \"Poison of the Darkened Mind\"",
    "21": "Hawk Sign \"Clawed Kidnapping\"",
    "22": "Hawk Sign \"Clawed Kidnapping\"",
    "23": "Hawk Sign \"Clawed Kidnapping\"",
    "24": "Hawk Sign \"Clawed Kidnapping\"",
    "25": "Night-Blindness \"Deadly Song of the Night Sparrow\"",
    "26": "Night-Blindness \"Deadly Song of the Night Sparrow\"",
    "27": "Night-Blindness \"Deadly Song of the Night Sparrow\"",
    "28": "Night-Blindness \"Deadly Song of the Night Sparrow\"",
    "29": "Night Sparrow \"Song of the Dark\"",
    "30": "Night Sparrow \"Song of the Dark\"",
    "31": "Night Sparrow \"Song of the Dark\"",
    "32": "Spiritual Birth \"Conspiracy Pyramid\"",
    "33": "Spiritual Birth \"Conspiracy Pyramid\"",
    "34": "Spiritual Birth \"Conspiracy Pyramid\"",
    "35": "Spiritual Birth \"Conspiracy Pyramid\"",
    "36": "Origin Sign \"Ephemerality Infinite\"",
    "37": "Origin Sign \"Ephemerality Infinite\"",
    "38": "Origin Sign \"Ephemerality Infinite\"",
    "39": "Ambition Sign \"Buretsu Cruelty\"",
    "40": "Ambition Sign \"Masakado Rebellion\"",
    "41": "Ambition Sign \"Yoshimitsu Overturning\"",
    "42": "Ambition Sign \"General Headquarters World War\"",
    "43": "Land Sign \"Kusanagi-no-Tsurugi\"",
    "44": "Land Sign \"Yasakani-no-Magatama\"",
    "45": "Land Sign \"Yata-no-Kagami\"",
    "46": "Land Scheme \"Combined Force of the Treasures\"",
    "47": "Ending Sign \"Emperor's Heritage\"",
    "48": "Ending Sign \"Emperor's Heritage\"",
    "49": "Pseudo-History \"The Legend of Dreams\"",
    "50": "Pseudo-History \"The Legend of Dreams\"",
    "51": "Future \"Divine Plain\"",
    "52": "Future \"Divine Plain\"",
    "53": "Future \"Divine Plain\"",
    "54": "Dream Sign \"Dreamy Barrier\"",
    "55": "Dream Sign \"Dreamy Barrier\"",
    "56": "Dream Land \"Great Nightmare Barrier\"",
    "57": "Dream Land \"Great Nightmare Barrier\"",
    "58": "Spirit Sign \"Fantasy Seal -Explode-\"",
    "59": "Spirit Sign \"Fantasy Seal -Explode-\"",
    "60": "Scattered Spirit \"Fantasy Seal -Destruction-\"",
    "61": "Scattered Spirit \"Fantasy Seal -Destruction-\"",
    "62": "Dream Sign \"Reality-Sealing Circle\"",
    "63": "Dream Sign \"Reality-Sealing Circle\"",
    "64": "Divine Arts \"Omnidirectional Demon-Destroying Circle\"",
    "65": "Divine Arts \"Omnidirectional Dragon-Killing Circle\"",
    "66": "Spirit Sign \"Fantasy Seal -Mindless-\"",
    "67": "Spirit Sign \"Fantasy Seal -Mindless-\"",
    "68": "Migrating Spirit \"Fantasy Seal -Perfection-\"",
    "69": "Migrating Spirit \"Fantasy Seal -Perfection-\"",
    "70": "Boundary \"Duplex Danmaku Wall\"",
    "71": "Boundary \"Duplex Danmaku Wall\"",
    "72": "Great Barrier \"Hakurei Danmaku Wall\"",
    "73": "Great Barrier \"Hakurei Danmaku Wall\"",
    "74": "Divine Spirit \"Fantasy Seal -Teleport-\"",
    "75": "Divine Spirit \"Fantasy Seal -Teleport-\"",
    "76": "Divine Spirit \"Fantasy Seal -Teleport-\"",
    "77": "Magic Sign \"Andromeda\"",
    "78": "Magic Sign \"Andromeda\"",
    "79": "Magic Space \"Oort Cloud\"",
    "80": "Magic Space \"Oort Cloud\"",
    "81": "Magic Sign \"Stardust Rondo\"",
    "82": "Magic Sign \"Stardust Rondo\"",
    "83": "Black Magic \"Escape Velocity\"",
    "84": "Black Magic \"Escape Velocity\"",
    "85": "Love Sign \"Stolen Lasers\"",
    "86": "Love Sign \"Stolen Lasers\"",
    "87": "Love Storm \"Laser Frenzy\"",
    "88": "Love Storm \"Laser Frenzy\"",
    "89": "Love Sign \"Ultra Spark\"",
    "90": "Love Sign \"Ultra Spark\"",
    "91": "Loving Heart \"Death Spark\"",
    "92": "Loving Heart \"Death Spark\"",
    "93": "Light Sign \"Hellray Spark\"",
    "94": "Light Sign \"Hellray Spark\"",
    "95": "Light Blast \"Shoot the Stars\"",
    "96": "Light Blast \"Shoot the Stars\"",
    "97": "Magicannon \"End Spark\"",
    "98": "Magicannon \"End Spark\"",
    "99": "Magicannon \"End Master Spark\"",
    "100": "Wave Sign \"Hypnotic Trance\"",
    "101": "Wave Sign \"Hypnotic Trance\"",
    "102": "Illusion Wave \"Mind Control\"",
    "103": "Illusion Wave \"Mind Control\"",
    "104": "Lunatic Sign \"Focal Shift\"",
    "105": "Lunatic Sign \"Focal Shift\"",
    "106": "Lunatic Gaze \"Lunatic Blindness\"",
    "107": "Lunatic Gaze \"Lunatic Blindness\"",
    "108": "Loafing Sign \"Heartbeat Stop\"",
    "109": "Loafing Sign \"Heartbeat Stop\"",
    "110": "Indolence \"Brain's Shutdown\"",
    "111": "Indolence \"Brain's Shutdown\"",
    "112": "Spread Sign \"Missing Moon\"",
    "113": "Spread Sign \"Missing Moon\"",
    "114": "Spread Sign \"Missing Moon\"",
    "115": "Spread Sign \"Missing Moon\"",
    "116": "Lunar Eyes \"Lunatic Soldier's Assault\"",
    "117": "Lunar Eyes \"Lunatic Soldier's Assault\"",
    "118": "Lunar Eyes \"Lunatic Soldier's Assault\"",
    "119": "Spacesphere \"Encapsulated Dreams\"",
    "120": "Spacesphere \"Encapsulated Dreams\"",
    "121": "Spacesphere \"Encapsulated Dreams\"",
    "122": "Spacesphere \"Encapsulated Dreams\"",
    "123": "Awakened God \"A Gods Eternal Dream\"",
    "124": "Awakened God \"A Gods Eternal Dream\"",
    "125": "God Sign \"Genes of Faulty Celestials\"",
    "126": "God Sign \"Genes of Faulty Celestials\"",
    "127": "Revival \"The Con-way of Life\"",
    "128": "Revival \"The Con-way of Life\"",
    "129": "Resurrection \"Ongoing Pain\"",
    "130": "Resurrection \"Ongoing Pain\"",
    "131": "Leading God \"Brain Explosion\"",
    "132": "Leading God \"Brain Explosion\"",
    "133": "Mind of God \"Delusional Thought\"",
    "134": "Mind of God \"Delusional Thought\"",
    "135": "Curse of the Heavens \"Burned on Impact\"",
    "136": "Curse of the Heavens \"Burned on Impact\"",
    "137": "Curse of the Heavens \"Burned on Impact\"",
    "138": "Curse of the Heavens \"Burned on Impact\"",
    "139": "Esoterica \"The Final Grave\"",
    "140": "Esoterica \"The Final Grave\"",
    "141": "Esoterica \"The Final Grave\"",
    "142": "Esoterica \"The Final Grave\"",
    "143": "Forbidden Spell \"Immortality Breaker\"",
    "144": "Forbidden Spell \"Immortality Breaker\"",
    "145": "Forbidden Spell \"Immortality Breaker\"",
    "146": "Forbidden Spell \"Immortality Breaker\"",
    "147": "Medicine Sign \"Insomnia Pill\"",
    "148": "Medicine Sign \"Insomnia Pill\"",
    "149": "Medicine Sign \"Insomnia Pill\"",
    "150": "Medicine Sign \"Insomnia Pill\"",
    "151": "Impossible Nightmare \"Curse of the Dragon's Jewel\"",
    "152": "Impossible Nightmare \"Curse of the Dragon's Jewel\"",
    "153": "Lucid Treasure \"Dragon's Dream Jewel\"",
    "154": "Lucid Treasure \"Dragon's Dream Jewel\"",
    "155": "Impossible Nightmare \"Stone Bowl filled with Tears\"",
    "156": "Impossible Nightmare \"Stone Bowl filled with Tears\"",
    "157": "Lucid Treasure \"Unbreakable Diamond\"",
    "158": "Lucid Treasure \"Unbreakable Diamond\"",
    "159": "Impossible Nightmare \"Blanket of Fire\"",
    "160": "Impossible Nightmare \"Blanket of Fire\"",
    "161": "Lucid Treasure \"Burning Bed\"",
    "162": "Lucid Treasure \"Burning Bed\"",
    "163": "Impossible Nightmare \"Forever Living, Forever Trapped\"",
    "164": "Impossible Nightmare \"Forever Living, Forever Trapped\"",
    "165": "Lucid Treasure \"Immortal Shackles\"",
    "166": "Lucid Treasure \"Immortal Shackles\"",
    "167": "Impossible Nightmare \"Rainbow of Life and Death\"",
    "168": "Impossible Nightmare \"Rainbow of Life and Death\"",
    "169": "Lucid Treasure \"Black Hole of Refracting Light\"",
    "170": "Lucid Treasure \"Black Hole of Refracting Light\"",
    "191": "Immortal Past \"Drinking of Cursed Elixir\"",
    "192": "Reincarnation \"Eternal Bridge of Pain\"",
    "193": "Immortal Future \"Blazing Earth\"",
    "194": "Lunar Cycle \"Rotating Phases\"",
    "195": "Immortal Moon \"Heavenly Bird\"",
    "196": "Railway \"Train to the Lunar Sea\"",
    "197": "Boundaries \"Hidden Capital of Lunarians\"",
    "198": "Entrapment \"Moon Princess's Suffering\"",
    "199": "Lunar Landing \"Difficult Intrusion\"",
    "200": "Tragic Disaster \"Crashing Spacecraft\"",
    "201": "Explosion \"Unkown Moon Volcano\"",
    "202": "\"Lunar Nightmare\"",
    "203": "\"The Prison of the Moon\"",
    "204": "\"Imperishable Shooting\"",
    "205": "\"Unseasonal Butterfly Storm\"",
    "206": "\"Blind Nightbird\"",
    "207": "\"Emperor of the Land of the Rising Sun\"",
    "208": "\"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)\"",
    "209": "\"Heaven Spider's Butterfly-Capturing Web\"",
    "210": "\"Tree-Ocean of Hourai\"",
    "211": "\"Phoenix Rebirth\"",
    "212": "\"Ancient Duper\"",
    "213": "\"Total Purification\"",
    "214": "\"Fantasy Nature\"",
    "215": "\"Blazing Star\"",
    "216": "\"Deflation World\"",
    "217": "\"Matsuyoi-Reflecting Satellite Slash\"",
    "218": "\"The Phantom of the Grand Guignol\"",
    "219": "\"Scarlet Destiny\"",
    "220": "\"Saigyouji Parinirvana\"",
    "221": "\"Profound Danmaku Barrier -Phantasm, Foam, and Shadow-\""
}