{
    "0": "Grave Sign \"Graveyard Shift\"",
    "2": "Grave Sign \"Accelerated Grave Construction\"",
    "4": "Death Sign \"Buried Alive\"",
    "6": "Death Sign \"Suffocating Earth\"",
    "8": "Poison Sign \"Expanding Poison in your Blood\"",
    "10": "Poison Sign \"Replacing Blood with Poison\"",
    "12": "Disease Sign \"Fast-Spreading Plague\"",
    "16": "Plague Sign \"Bacterial Infection\"",
    "18": "Plague Sign \"Self-Replicating Virus\"",
    "20": "Drought Sign \"Water Evaporation\"",
    "22": "Drought Sign \"Blazing Sun over the Empty Lake\"",
    "23": "Drought Sign \"Lifeless Desert of Dust\"",
    "24": "Lost Sun \"Energy Deficiency\"",
    "26": "Lost Sun \"Broken Energy Cycle\"",
    "27": "Lost Sun \"Lost Energy of the Sun\"",
    "28": "Soul Sign \"Forgotten Souls of Dead Cattle\"",
    "30": "Soul Sign \"Vengeful Souls of Murdered Wildlife\"",
    "31": "Soul Sign \"Fading Souls of the Population\"",
    "32": "Explosive Sign \"Strategic Landmine Field\"",
    "36": "Blitzkrieg \"Assault from the Back\"",
    "38": "Blitzkrieg \"Occupation of Foreign Land\"",
    "39": "Blitzkrieg \"Rapid Destruction of Homes\"",
    "40": "Sturmwaffe \"High-Accuracy Killing-Machine\"",
    "44": "Sadness \"Piercing Tears\"",
    "46": "Sadness \"Bloodshot Tear Rain\"",
    "48": "Anger \"Contained Hate\"",
    "50": "Anger \"Berserker's Frenzy\"",
    "52": "Fear \"Sword of Damocles\"",
    "54": "Fear \"The Inevitable Sword of Damocles\"",
    "56": "Negativity \"7 Deadly Sins\"",
    "58": "Negativity \"The Sins of Humanity\"",
    "60": "Star of Bethlehem \"Prophecy of Greatness\"",
    "62": "Star of Bethlehem \"Birth of the Messiah\"",
    "64": "Wheel of Life \"Death and Rebirth\"",
    "66": "Wheel of Life \"Nirvana through Enlightenment\"",
    "68": "Boundless Shackles \"Affirmative Grasp over Dreams\"",
    "70": "Boundless Shackles \"Tight Grip holding Dreams Together\"",
    "72": "Omen \"Grand Dream-Cleaver\"",
    "74": "Omen \"Dreamland Splitter\"",
    "76": "\"Dream Realm's Broken Heart\"",
    "80": "\"Rebirth Overseen by Shining Lights\"",
    "84": "\"4 Royal Virtues - Lucidia Kaiza\"",
    "88": "Pestilence \"Clogged Bloodflow\"",
    "89": "War \"Nuclear Warhead Crisis\"",
    "90": "Death \"Haunting Spirits of the Past\"",
    "91": "Hollow \"Evil Expulsion\"",
    "92": "Unchained \"Endless Wanderer\"",
    "93": "Searching \"Lost Purpose\"",
    "94": "Heartless \"Empty Burning Chest\"",
    "95": "Loneliness \"Cornerstones of Friendship\"",
    "96": "Soul \"Newborn Soul from Memories\"",
    "97": "Dreams \"Rebellious Nature\"",
    "98": "\"Blizzard Inside My Heart\"",
    "99": "\"Journey to the Depths of the Soul\"",
    "100": "\"The Dreams of Jessica Puella Kaisa\""
}