{
    "0": "Grave Sign \"Graveyard Shift\"",
    "2": "Grave Sign \"Accelerated Grave Construction\"",
    "4": "Death Sign \"Buried Alive\"",
    "6": "Death Sign \"Suffocating Earth\"",
    "8": "Poison Sign \"Expanding Poison in your Blood\"",
    "10": "Poison Sign \"Replacing Blood with Poison\"",
    "12": "Disease Sign \"Fast-Spreading Plague\"",
    "16": "Plague Sign \"Bacterial Infection\"",
    "18": "Plague Sign \"Self-Replicating Virus\"",
    "20": "Drought Sign \"Water Evaporation\"",
    "22": "Drought Sign \"Blazing Sun over the Empty Lake\"",
    "23": "Drought Sign \"Lifeless Desert of Dust\"",
    "24": "Lost Sun \"Energy Deficiency\"",
    "26": "Lost Sun \"Broken Energy Cycle\"",
    "27": "Lost Sun \"Lost Energy of the Sun\"",
    "28": "Soul Sign \"Forgotten Souls of Dead Cattle\"",
    "30": "Soul Sign \"Vengeful Souls of Murdered Wildlife\"",
    "31": "Soul Sign \"Fading Souls of the Population\"",
    "32": "Tortoise Sign \"Tortoiseshell Hell\"",
    "36": "Oni Sign \"Beasts Attacking from the Rear\"",
    "38": "Oni Sign \"Mangy Beasts Attacking from the Rear\"",
    "39": "Oni Sign \"Devilish Beasts Attacking from the Rear\"",
    "40": "Dragon Sign \"Dragon Crest Bullets\"",
    "44": "Haniwa \"Archer Haniwa\"",
    "46": "Haniwa \"Skilled Archer Haniwa\"",
    "48": "Haniwa \"Fencer Haniwa\"",
    "50": "Haniwa \"Skilled Fencer Haniwa\"",
    "52": "Haniwa \"Cavalry Haniwa\"",
    "54": "Haniwa \"Skilled Cavalry Haniwa\"",
    "56": "Haniwa \"Hollow Inexhaustible Troops\"",
    "58": "Haniwa \"Undefeated Inexhaustible Troops\"",
    "60": "Square Shape \"Square-Shaped Sculpting Art\"",
    "62": "Square Shape \"Square Creature\"",
    "64": "Circular Shape \"Perfect Circle Sculpting Art\"",
    "66": "Circular Shape \"Circle Creature\"",
    "68": "Linear Shape \"Line-Shaped Sculpting Art\"",
    "70": "Linear Shape \"Linear Creature\"",
    "72": "Haniwa \"Horse-and-Rider Idol Sculpting Art\"",
    "74": "Haniwa \"Idol Creature\"",
    "76": "\"Oni-Shaped Sculpting Art\"",
    "80": "\"Geometric Creature\"",
    "84": "\"Idola Diabolus\"",
    "88": "Bloody Battle \"Watershed of Blood\"",
    "89": "Bloody Battle \"Hell Realm Sight-Line\"",
    "90": "Bloody Battle \"All-Spirit Oniwatari\"",
    "91": "Agile Skill \"Thrilling Shot\"",
    "92": "Agile Skill \"Lightning Neigh\"",
    "93": "Agile Skill \"Dense Crowd\"",
    "94": "Agile Skill \"Beast Epidemicity\"",
    "95": "Agile Skill \"Triangle Chase\"",
    "96": "Agile Skill \"Black Pegasus Meteor Shot\"",
    "97": "Agile Skill \"Muscle Explosion\"",
    "98": "\"Follow Me, Unafraid\"",
    "99": "\"Oni-Shaped Hoi Polloi\"",
    "100": "\"Deeds of Devilish Beasts\""
}