{
    "0": "Frost Sign \"Crystallized Snowflake\"",
    "1": "Frost Sign \"Crystallized Snowflake -Lunatic-\"",
    "2": "Cold Sign \"Leftover Snowball Fight -Easy-\"",
    "3": "Cold Sign \"Leftover Snowball Fight\"",
    "4": "Cold Sign \"Leftover Snowball Fight -Hard-\"",
    "5": "Cold Sign \"Leftover Snowball Fight -Lunatic-\"",
    "6": "Winter Sign \"Forgotten Winter Flower -Easy-\"",
    "7": "Winter Sign \"Forgotten Winter Flower\"",
    "8": "White Sign \"Frozen Flower Loss\"",
    "9": "Mystic Sign \"Life and Death in Winter\"",
    "10": "Hermit Sign \"Hatcher Egg -Easy-\"",
    "11": "Hermit Sign \"Hatcher Egg\"",
    "12": "Hermit Sign \"Rainbow Kitten\"",
    "13": "Hermit Sign \"Rainbow Kitten -Lunatic-\"",
    "14": "Shikigami Sign \"Starry Seiman -Easy-\"",
    "15": "Shikigami Sign \"Starry Seiman\"",
    "16": "Yin Yang \"Insect Chaser\"",
    "17": "Yin Yang \"Butterfly Effect\"",
    "18": "Heaven Sign \"Mayohiga Shelter -Easy-\"",
    "19": "Heaven Sign \"Mayohiga Shelter\"",
    "20": "Flight Sign \"Village Safety\"",
    "21": "Servant Sign \"Unwelcome Village Guest\"",
    "22": "Hermit Sign \"Butterfly Fields -Easy-\"",
    "23": "Hermit Sign \"Butterfly Fields\"",
    "24": "Oni Sign \"Butterfly Borders\"",
    "25": "Direction Sign \"Boundary of Butterfly and Insect\"",
    "26": "Puppeteer Sign \"Strings off a Stem\"",
    "27": "Puppeteer Sign \"Strings off a Stem -Lunatic-\"",
    "28": "Murder Sign \"Murderous French Dolls -Easy-\"",
    "29": "Murder Sign \"Murderous French Dolls\"",
    "30": "Murder Sign \"Murderous French Dolls -Hard-\"",
    "31": "Murder Sign \"Murderous Orléans Dolls\"",
    "32": "Scarlet Sign \"Double-Crossed Dutch Dolls -Easy-\"",
    "33": "Scarlet Sign \"Double-Crossed Dutch Dolls\"",
    "34": "Snow Sign \"Frozen Russian Dolls Dolls\"",
    "35": "Snow Sign \"Frozen Russian Dolls -Lunatic-\"",
    "36": "Darkness Sign \"Rainy London Dolls -Easy-\"",
    "37": "Darkness Sign \"Rainy London Dolls\"",
    "38": "Cycle Sign \"Peaked Tibetan Dolls\"",
    "39": "Elegant Sign \"Lovely Kyoto Dolls\"",
    "40": "Malediction \"Magically Friendly Shanghai Dolls -Easy-\"",
    "41": "Malediction \"Magically Friendly Shanghai Dolls\"",
    "42": "Malediction \"Magically Friendly Shanghai Dolls -Hard-\"",
    "43": "Malediction \"Immortal Hourai Dolls\"",
    "44": "Noisy Sign \"Phantom Dinning -Easy-\"",
    "45": "Noisy Sign \"Phantom Dinning\"",
    "46": "Noisy Sign \"Live Poltergeist\"",
    "47": "Noisy Sign \"Live Poltergeist -Lunatic-\"",
    "48": "String Performance \"Guarneri del Gesù -Easy-\"",
    "49": "String Performance \"Guarneri del Gesù\"",
    "50": "Divine Strings \"Stradivarius\"",
    "51": "Fake Strings \"Pseudo Stradivarius\"",
    "52": "Trumpet Spirit \"Hino Phantasm -Easy-\"",
    "53": "Trumpet Spirit \"Hino Phantasm\"",
    "54": "Nether Trumpet \"Ghost Clifford\"",
    "55": "Nether Trumpet \"Ghost Clifford -Lunatic-\"",
    "56": "Nether Keys \"Fazioli Nether Performance -Easy-\"",
    "57": "Nether Keys \"Fazioli Nether Performance\"",
    "58": "Key Spirit \"Bösendorfer Divine Performance\"",
    "59": "Key Spirit \"Bösendorfer Divine Performance -Lunatic-\"",
    "60": "Funeral Concert \"Prism Concerto -Easy-\"",
    "61": "Funeral Concert \"Prism Concerto\"",
    "62": "Noisy Funeral \"Stygian Riverside\"",
    "63": "Noisy Funeral \"Stygian Riverside -Lunatic-\"",
    "64": "Great Funeral Concert \"Spirit Wheel Concerto Grosso -Easy-\"",
    "65": "Great Funeral Concert \"Spirit Wheel Concerto Grosso\"",
    "66": "Great Funeral Concert \"Spirit Wheel Concerto Grosso: Revised\"",
    "67": "Great Funeral Concert \"Spirit Wheel Concerto Grosso: Wondrous\"",
    "68": "Ghost Sword \"Spiritual Knife Dance -Easy-\"",
    "69": "Ghost Sword \"Spiritual Knife Dance\"",
    "70": "Preta Sword \"Sprits of Kitchen Knifes\"",
    "71": "Hungry King Sword \"Burning Souls of Swords\"",
    "72": "Hell Realm Sword \"Self-serving Buffet Slash -Easy-\"",
    "73": "Hell Realm Sword \"Self-serving Buffet Slash\"",
    "74": "Hell Fire Sword \"Feast of a Thousand Guests\"",
    "75": "Hell God Sword \"Gluttonous Monster at Feast\"",
    "76": "Animal Realm Sword \"Beastly Seperation of Wrath -Easy-\"",
    "77": "Animal Realm Sword \"Beastly Seperation of Wrath\"",
    "78": "Asura Sword \"Obsession with the Present World\"",
    "79": "Asura Sword \"Obsession with the Present World -Lunatic-\"",
    "80": "Human Realm Sword \"Ascension to Heaven -Easy-\"",
    "81": "Human Realm Sword \"Ascension to Heaven\"",
    "82": "Human Era Sword \"Burdened Heaven Pilgrimage\"",
    "83": "Human God Sword \"The Lie of Heaven\"",
    "84": "Heaven Sword \"Five Colors of the Deva -Easy-\"",
    "85": "Heaven Sword \"Five Colors of the Deva\"",
    "86": "Deva Realm Sword \"Seven Hakus New Groove\"",
    "87": "Heaven God Sword \"Madness of the Hakus\"",
    "88": "Six Realms Sword \"Cherry Blossom Blooming Flower -Easy-\"",
    "89": "Six Realms Sword \"Cherry Blossom Blooming Flower\"",
    "90": "Six Realms Sword \"Cherry Blossom Blooming Flower -Hard-\"",
    "91": "Six Realms Sword \"Cherry Blossom Blooming Flower -Lunatic-\"",
    "92": "Losing Hometown \"Village of Forgotten Souls -Hopeless Soul-\"",
    "93": "Losing Hometown \"Village of Self-Loss -Past Mistakes-\"",
    "94": "Losing Hometown \"Village of Self-Loss -Endless Path-\"",
    "95": "Losing Hometown \"Village of Self-Loss -End of Life-\"",
    "96": "Deadly Dance \"Regretful Dance -Confusion-\"",
    "97": "Deadly Dance \"Regretful Dance -Murdered Girl-\"",
    "98": "Deadly Dance \"Regretful Dance -Poisoned Monarch-\"",
    "99": "Deadly Dance \"Regretful Dance -Hell's Visit-\"",
    "100": "Crawling Sins \"Forgetful Mistake\"",
    "101": "Crawling Sins \"Gnawing Regret\"",
    "102": "Crawling Sins \"Deep-Rooted Trauma\"",
    "103": "Crawling Sins \"Engraved Depression\"",
    "104": "Subtle Melody \"Chasing Demons -False Soul-\"",
    "105": "Subtle Melody \"Chasing Demons -Ghost-\"",
    "106": "Subtle Melody \"Chasing Demons -Phantom Spirit-\"",
    "107": "Subtle Melody \"Chasing Demons -Divine Spirit-\"",
    "108": "Cherry Blossom Sign \"Perfect Netherworld Home -Seal-\"",
    "109": "Cherry Blossom Sign \"Perfect Netherworld Home -Self-Loss-\"",
    "110": "Cherry Blossom Sign \"Perfect Netherworld Home -Spring Sleep-\"",
    "111": "Cherry Blossom Sign \"Perfect Netherworld Home -Bloom-\"",
    "112": "\"Resurrection Butterfly -10%% Reflowering-\"",
    "113": "\"Resurrection Butterfly -30%% Reflowering-\"",
    "114": "\"Resurrection Butterfly -50%% Reflowering-\"",
    "115": "\"Resurrection Butterfly -80%% Reflowering-\"",
    "116": "Feline Sign \"Red and Blue Ceiling Climb\"",
    "117": "Kishin \"Soaring Bishamonten\"",
    "118": "Shikigami \"Blowing Winter Leaves\"",
    "119": "Shikigami \"Dining Hall of the General Gods\"",
    "120": "Shiki Brilliance \"Shikigami Calculation Grid\"",
    "121": "Shiki Brilliance \"Shikigami's Prison Contract\"",
    "122": "Shiki Brilliance \"Illusionary Phantasm\"",
    "123": "Shiki Shot \"Expanding Faith\"",
    "124": "Shiki Shot \"Misleading Trickery\"",
    "125": "Shikigami \"Chen's Playfield\"",
    "126": "\"Shikigami -Eternal Contract-\"",
    "127": "Illusion God \"Home between Worlds\"",
    "128": "Shikigami \"Mountains of Eternity\"",
    "129": "Shikigami \"Channeling Dakiniten\"",
    "130": "Barrier \"Chains of Dreams and Realism\"",
    "131": "Barrier \"Speed of Matter and Antimatter\"",
    "132": "Barrier \"Mesh of Light and Darkness\"",
    "133": "Evil Spirits \"Eternal Yin and Yang Struggle\"",
    "134": "Evil Spirits \"Sealed Away Trainride\"",
    "135": "Evil Spirits \"Bewitching Butterfly Living in the Zen Temple\"",
    "136": "Sinister Spirits \"Butterflies of Betrayal\"",
    "137": "Shikigami \"Ran Yakumo\"",
    "138": "\"Boundary of Humans and Youkai\"",
    "139": "Barrier \"Vague Border of Home and Suffering\"",
    "140": "Boundary of Wave and Particle"
}