{
    "0": "Tree Kicker \"Precious Leaves Falling Gently\"",
    "2": "Autumn Sun \"Fresh Crop Yield\"",
    "4": "Autumn Sun \"Lovely Crops On A Beautiful Day\"",
    "6": "Crop Sign \"Divine Growth\"",
    "8": "Bumper Crop \"Vined The Good Harvest\"",
    "10": "Fortune Sign \"Lucky Clover\"",
    "12": "Misfortune Sign \"Unlucky Clover\"",
    "14": "Bad Luck \"Broken Mirror\"",
    "16": "Shards \"Mirrored Fragments of Glass\"",
    "18": "Forbidden Ladder \"Above Threat\"",
    "20": "Ladder Festival \"Salt-Throwing Ladder Feast\"",
    "22": "Raven Sign \"Scattering Feathers\"",
    "24": "Raven Sign \"Black Feathers of Bad Omen\"",
    "26": "Flashbang \"Blinding Coverfire\"",
    "28": "Flashbang \"Brightening Flash\"",
    "30": "New Invention \"Laser Grid\"",
    "32": "New Invention \"Tripwire Laser Catch\"",
    "33": "New Invention \"Tripwire Laser Catch - Deluxe\"",
    "34": "Pop! \"Bubble Blowing Blowout\"",
    "36": "Pop! \"Bubble Dragon Burst!\"",
    "37": "Pop! \"Bubble Dragon Burst!\"",
    "38": "Water Gun \"Spray Burst Nozzle\"",
    "40": "Water Gun \"Machine Gun Spray\"",
    "41": "Water Gun \"Machine Gun Spray Extreme\"",
    "42": "Crossroad Sign \"Crossroads of Heaven\"",
    "44": "Crossroad Sign \"Saruta Cross\"",
    "46": "Wind God \"Wind God's Leaf-Veiling\"",
    "48": "Wind God \"Tengu's Fall Wind\"",
    "49": "Wind God \"Storm Day\"",
    "50": "\"Illusionary Dominance\"",
    "51": "\"Illusionary Dominance\"",
    "52": "\"Peerless Wind God\"",
    "53": "Blockade Sign \"Mountain God's Procession\"",
    "55": "Blockade Sign \"Advent of the Divine Grandson\"",
    "56": "Blockade Sign \"Terukuni Shining Through Heaven and Earth\"",
    "57": "Esoterica \"Gray Thaumaturgy\"",
    "59": "Esoterica \"Forgotten Ritual\"",
    "60": "Esoterica \"Secretly Inherited Art of Danmaku\"",
    "61": "Miracle \"Daytime Guest Stars\"",
    "63": "Miracle \"Night with Bright Guest Stars\"",
    "64": "Miracle \"Night with Overly Bright Guest Stars\"",
    "65": "Sea Opening \"The Day the Sea Split\"",
    "67": "Sea Opening \"Moses' Miracle\"",
    "68": "Sea Opening \"Moses' Miracle\"",
    "69": "Preparation \"Star Ritual to Call the Godly Winds\"",
    "71": "Preparation \"Summon Takeminakata\"",
    "73": "Miracle \"God's Wind\"",
    "75": "Great Miracle \"Yasaka's Divine Wind\"",
    "77": "Divine Festival \"Expanded Onbashira\"",
    "79": "Weird Festival \"Medoteko Boisterous Dance\"",
    "80": "Weird Festival \"Medoteko Boisterous Dance\"",
    "81": "Rice Porridge in Tube \"God's Rice Porridge\"",
    "83": "Forgotten Grain \"Unremembered Crop\"",
    "84": "Divine Grain \"Divining Crop\"",
    "85": "Sacrifice Sign \"Misayama Hunting Shrine Ritual\"",
    "87": "Mystery \"Kuzui Clear Water\"",
    "88": "Mystery \"Yamato Torus\"",
    "89": "Heaven's Stream \"Miracle of Otensui\"",
    "91": "Heaven's Dragon \"Source of Rains\"",
    "93": "\"Mountain of Faith\"",
    "95": "\"Divine Virtues of Wind God\"",
    "97": "God Sign \"Beautiful Spring like Suiga\"",
    "98": "God Sign \"Ancient Fate Linked by Cedars\"",
    "99": "God Sign \"Omiwatari that God Walked\"",
    "100": "Party Start \"Two Bows, Two Claps, and One Bow\"",
    "101": "Native God \"Lord Long-Arm and Lord Long-Leg\"",
    "102": "Divine Tool \"Moriya's Iron Ring\"",
    "103": "Spring Sign \"Jade of the Horrid River\"",
    "104": "Frog Hunt \"The Snake Eats the Croaking Frog\"",
    "105": "Native God \"Seven Stones and Seven Trees\"",
    "106": "Native God \"Froggy Braves the Wind and Rain\"",
    "107": "Native God \"Red Frogs of Houei Four\"",
    "108": "\"Suwa War ~ Native Myth vs. Central Myth\"",
    "109": "Scourge Sign \"Mishaguji-sama\""
}