{
    "0": "Tree Kicker \"Precious Leaves Falling Gently\"",
    "2": "Autumn Sun \"Fresh Crop Yield\"",
    "4": "Autumn Sun \"Lovely Crops On A Beautiful Day\"",
    "6": "Crop Sign \"Divine Growth\"",
    "8": "Bumper Crop \"Vined The Good Harvest\"",
    "10": "Fortune Sign \"Lucky Clover\"",
    "12": "Misfortune Sign \"Unlucky Clover\"",
    "14": "Bad Luck \"Broken Mirror\"",
    "16": "Shards \"Mirrored Fragments of Glass\"",
    "18": "Forbidden Ladder \"Above Threat\"",
    "20": "Ladder Festival \"Salt-Throwing Ladder Feast\"",
    "22": "Raven Sign \"Scattering Feathers\"",
    "24": "Raven Sign \"Black Feathers of Bad Omen\"",
    "26": "Flashbang \"Blinding Coverfire\"",
    "28": "Flashbang \"Brightening Flash\"",
    "30": "New Invention \"Laser Grid\"",
    "32": "New Invention \"Tripwire Laser Catch\"",
    "33": "New Invention \"Tripwire Laser Catch - Deluxe\"",
    "34": "Pop! \"Bubble Blowing Blowout\"",
    "36": "Pop! \"Bubble Dragon Burst!\"",
    "37": "Pop! \"Bubble Dragon Burst!\"",
    "38": "Water Gun \"Spray Burst Nozzle\"",
    "40": "Water Gun \"Machine Gun Spray\"",
    "41": "Water Gun \"Machine Gun Spray Extreme\"",
    "42": "Breeze Sign \"Gentle Winds Blowing Leaves\"",
    "44": "Breeze Sign \"Storm-Crossing Leaf Scatter\"",
    "46": "Wind God \"Hidden Path in Autumn Leaf\"",
    "48": "Wind God \"Carving Road of Leaf Pile\"",
    "49": "Wind God \"Saw Blade Hidden in Leaves\"",
    "50": "\"Wind God Girl\"",
    "51": "\"Wind God Girl\"",
    "52": "\"Tengu Frenzy\"",
    "53": "Tengu Illusion \"Secret Heart of Bullet\"",
    "55": "Tengu Illusion \"Sneaky Pathway Shrink\"",
    "56": "Tengu Illusion \"Deceiving Size Change\"",
    "57": "Super Star \"Pop Star Fun Pack\"",
    "59": "Super Star \"Pop Star Ultra\"",
    "60": "Super Star \"Planet Star Pop Cake!\"",
    "61": "Fan Remix \"Nico Nico Douga\"",
    "63": "Fan Remix \"Nico Nico Douga Gaiden\"",
    "64": "Fan Remix \"A Song for Nico Nico Dougaholics\"",
    "65": "Spinning Top \"How to Bey a Blade\"",
    "67": "Spinning Top \"Moses' Whirling Splitter\"",
    "68": "Spinning Top \"Moses' Red Sea Miracle\"",
    "69": "Zohar Sign \"Conduit of Infinite Power\"",
    "71": "Zohar Sign \"Turning Gears of God\"",
    "73": "Miracle Laser \"Kamehameha\"",
    "75": "Great Laser \"Dragon's Spherical Power\"",
    "77": "Divine Festival \"Onbashira Assault\"",
    "79": "Weird Festival \"Divine Pillar Pain Festival\"",
    "80": "Weird Festival \"Divine Pillar Pain Festival\"",
    "81": "Harvest Crop \"Rainbow Rice Rain\"",
    "83": "Forgotten Harvest \"Unremembered Rice\"",
    "84": "Divine Harvest \"Pray Upon Good Yields\"",
    "85": "Sacrifice Sign \"Blades Befell The Mountain\"",
    "87": "Mystery \"Stab The River\"",
    "88": "Mystery \"Heaven-Mountain Cycle\"",
    "89": "Heavenly Firmament \"Drizzle Of The Sky\"",
    "91": "Heavenly Firmament \"Broken Downpour\"",
    "93": "\"Mountain of Denial\"",
    "95": "\"Deny Thy Nature - Feel The Wrath\"",
    "97": "God Sign \"Beautiful Spring like Suiga\"",
    "98": "God Sign \"Ancient Fate Linked by Cedars\"",
    "99": "God Sign \"Omiwatari that God Walked\"",
    "100": "Party Start \"Two Bows, Two Claps, and One Bow\"",
    "101": "Native God \"Lord Long-Arm and Lord Long-Leg\"",
    "102": "Divine Tool \"Moriya's Iron Ring\"",
    "103": "Spring Sign \"Jade of the Horrid River\"",
    "104": "Frog Hunt \"The Snake Eats the Croaking Frog\"",
    "105": "Native God \"Seven Stones and Seven Trees\"",
    "106": "Native God \"Froggy Braves the Wind and Rain\"",
    "107": "Native God \"Red Frogs of Houei Four\"",
    "108": "\"Suwa War ~ Native Myth vs. Central Myth\"",
    "109": "Scourge Sign \"Mishaguji-sama\""
}