{
    "0": "Evil Bullet \"Bullet Warp\"",
    "2": "Bullet Sign \"Quickscope Sniper\"",
    "5": "Bullet Sign \"No-Miss Aimbot\"",
    "6": "Gun Sign \"Nightmare Shooter\"",
    "9": "Gun Sign \"Nightmare Shooter\"",
    "10": "Rabbit Sign \"Blood Berry Dango\"",
    "12": "Rabbit Sign \"Very Berry Dango\"",
    "14": "Rabbit Sign \"Dango Poison\"",
    "18": "Moon-Viewing \"Yearly Stolen Moon\"",
    "21": "Moon-Viewing Saké \"Nightmare Drunkard\"",
    "22": "Sleep Sign \"Sleep Deprivation\"",
    "24": "Sleep Sign \"Bloodshot Red Eyes\"",
    "26": "Dream Sign \"Sweet Embrace of Dreams\"",
    "28": "Dream Sign \"Bad Dream's Harsh Hold\"",
    "29": "Dream Sign \"Suffocating Nightmare Grasp\"",
    "30": "Night Sign \"Midnight's Full Moon\"",
    "32": "Night Sign \"Late Night's Crescent Moon\"",
    "34": "Sleep Sign \"Dream Prison\"",
    "36": "Sleep Sign \"Artifical Straight Jacket\"",
    "37": "Sleep Sign \"Paralyzing Claustrophobia\"",
    "38": "Deep Dream Sign \"Unwound Dream Barrier\"",
    "42": "Orb Sign \"Army Deployment\"",
    "44": "Orb Sign \"Unorganized Army Call\"",
    "46": "Orb Sign \"Heat Seeking Spirits\"",
    "48": "Orb Sign \"Soul Seeking Spirits\"",
    "50": "Orb Sign \"Rapid Fire Soul Emission\"",
    "52": "Orb Sign \"Godly Soul Spawner\"",
    "54": "\"Forgotten Dream Heron\"",
    "58": "Hell Sign \"Hell's Volcano\"",
    "60": "Hell Sign \"Volcano under Pressure\"",
    "62": "Hell Sign \"Fiery Walls of Hell\"",
    "64": "Hell Sign \"Burning Cage\"",
    "66": "Hellfire \"The Sun of Hell\"",
    "69": "Hellfire \"Grazeful Sun\"",
    "70": "Inferno \"Purgatory Prison\"",
    "74": "\"Midnight Fever\"",
    "76": "\"Nightfall Delirium\"",
    "78": "\"Pure Shine of Anger\"",
    "82": "\"Pent-Up Rage\"",
    "86": "\"Spirit Summon of Yesterday\"",
    "88": "\"World of Dream Control\"",
    "90": "\"Madness of your Mind\"",
    "94": "\"Forgotten Flower Turn\"",
    "98": "\"Mental Cage\"",
    "101": "\"Trapped Mind in Suffering\"",
    "102": "Pure Sign \"A Pure Wish to the Tree\"",
    "104": "Pure Sign \"Pure Hatred towards Life\"",
    "106": "Capture Sign \"Purifying Dreamcatcher\"",
    "107": "Surreal Sign \"Chaotic Dream Merge\"",
    "108": "Crawling Chaos \"Final Portal Ceremony\"",
    "109": "Divine Symbol \"Scarlet Laurel Leaf\"",
    "110": "Moon Sign \"Tide of Rage\"",
    "111": "Moon Sign \"Gamma Radiation\"",
    "112": "\"Dual-Bladed Knife For Murder\"",
    "113": "Obscene Sign \"The Curse of the Mob\"",
    "114": "Forbidden Medicine \"Penglai's Medicine\"",
    "115": "Five Offerings \"Three Suns and Moonlight\"",
    "116": "\"The Danmaku that shall Murder Chang'e\"",
    "117": "\"Lunar Enchantment -The Moon of the Table-\"",
    "118": "\"Final Duel of Rivals\"",
    "45": "Orb Sign \"Ultimate Army Attack\""
}