{
    "0": "Evil Bullet \"Bullet Warp\"",
    "2": "Bullet Sign \"Quickscope Sniper\"",
    "5": "Bullet Sign \"No-Miss Aimbot\"",
    "6": "Gun Sign \"Nightmare Shooter\"",
    "9": "Gun Sign \"Nightmare Shooter\"",
    "10": "Rabbit Sign \"Blood Berry Dango\"",
    "12": "Rabbit Sign \"Very Berry Dango\"",
    "14": "Rabbit Sign \"Dango Poison\"",
    "18": "Moon-Viewing \"Yearly Stolen Moon\"",
    "21": "Moon-Viewing Saké \"Nightmare Drunkard\"",
    "22": "Sleep Sign \"Sleep Deprivation\"",
    "24": "Sleep Sign \"Bloodshot Red Eyes\"",
    "26": "Dream Sign \"Sweet Embrace of Dreams\"",
    "28": "Dream Sign \"Bad Dream's Harsh Hold\"",
    "29": "Dream Sign \"Suffocating Nightmare Grasp\"",
    "30": "Night Sign \"Midnight's Full Moon\"",
    "32": "Night Sign \"Late Night's Crescent Moon\"",
    "34": "Sleep Sign \"Dream Prison\"",
    "36": "Sleep Sign \"Artifical Straight Jacket\"",
    "37": "Sleep Sign \"Paralyzing Claustrophobia\"",
    "38": "Deep Dream Sign \"Unwound Dream Barrier\"",
    "42": "Orb Sign \"Disorderly Flock's Curse\"",
    "44": "Orb Sign \"Disorderly Flock's Reverse Curse\"",
    "46": "Orb Sign \"Impure Body Detection Mines\"",
    "48": "Orb Sign \"Impure Body Detection Mines V2\"",
    "50": "Orb Sign \"Shotgun Coronation of the Gods\"",
    "52": "Orb Sign \"Shining Shotgun Coronation of the Gods\"",
    "54": "\"One-Winged White Heron\"",
    "58": "Hell Sign \"Hell Eclipse\"",
    "60": "Hell Sign \"Eclipse of Hell\"",
    "62": "Hell Sign \"Flash and Stripe\"",
    "64": "Hell Sign \"Star and Stripe\"",
    "66": "Hellfire \"Graze Inferno\"",
    "69": "Hellfire \"Infernal Essence of Grazing\"",
    "70": "Inferno \"Striped Abyss\"",
    "74": "\"Fake Apollo\"",
    "76": "\"Apollo Hoax Theory\"",
    "78": "\"Pure Light of the Palm\"",
    "82": "\"Murderous Lilies\"",
    "86": "\"Primordial Divine Spirit World\"",
    "88": "\"Modern Divine Spirit World\"",
    "90": "\"Trembling, Shivering Star\"",
    "94": "\"Pristine Lunacy\"",
    "98": "\"Overflowing Blemishes\"",
    "101": "\"Refinement of Earthen Impurity\"",
    "102": "Pure Sign \"Purely Bullet Hell\"",
    "104": "Pure Sign \"A Pristine Danmaku Hell\"",
    "106": "Butterfly \"Butterfly Supplantation\"",
    "107": "Super-Express \"Dream Express\"",
    "108": "Crawling Dream \"Creeping Bullet\"",
    "109": "Otherworld \"Ōmagatoki\"",
    "110": "Earth \"Impurity Within One's Body\"",
    "111": "Moon \"Apollo Reflection Mirror\"",
    "112": "\"Simple Danmaku for Cornering a Trapped Rat\"",
    "113": "Otherworld \"Hell's Non-Ideal Danmaku\"",
    "114": "Earth \"Rain Falling in Hell\"",
    "115": "Moon \"Lunatic Impact\"",
    "116": "\"Pristine Danmaku for Killing a Person\"",
    "117": "\"Trinitarian Rhapsody\"",
    "118": "\"First and Last Nameless Danmaku\"",
    "45": "Orb Sign \"Disorderly Flock's Duplex Curse\""
}