{
    "0": "Ice Sign \"Grand Ice Fairy Finale\"",
    "2": "Water Sign \"Underwater Whirlpool Trap\"",
    "6": "Scale Sign \"Boat Sinker\"",
    "8": "Scale Sign \"Great Waves of the Ocean\"",
    "9": "Scale Sign \"Tsunami Overwhelm\"",
    "10": "Flight Sign \"Headless Chicken\"",
    "14": "Neck Sign \"Laser Trapper\"",
    "16": "Neck Sign \"Laser Head Spinner\"",
    "18": "Flying Head \"Broken Head Trauma\"",
    "20": "Flying Head \"Multiple Head Trauma\"",
    "21": "Flying Head \"Many Brain Theory\"",
    "22": "Flying Head \"Fearful Dullahan Night\"",
    "26": "Fang Sign \"Inverted Moon Teeth\"",
    "28": "Transformation \"Transformed Triangle\"",
    "30": "Transformation \"Star Pattern\"",
    "32": "Roar \"High-Pitched Howl\"",
    "34": "Roar \"Inverted Moon Cry\"",
    "36": "Wolf Sign \"Wolf Pouncer Bouncer\"",
    "38": "Sirius \"Lightspeed Pounce\"",
    "40": "Heikyoku \"Beautiful Bell Poem\"",
    "44": "Vengeful Spirit \"Grand Seeker of Sound\"",
    "46": "Vengeful Spirit \"Gatherer of Sound Score\"",
    "48": "Music Sign \"Musical Trap\"",
    "50": "Music Sign \"Cage of Lyrics\"",
    "51": "Music Sign \"Double Vocal Jail\"",
    "52": "Koto Sign \"Beloved Poem Echo\"",
    "56": "Echo Sign \"Heian's Feedback Loop\"",
    "58": "Echo Sign \"Eternal Amplifier\"",
    "60": "Koto Music \"Grand Inversion Musical\"",
    "62": "Koto Music \"Grand Inversion Musical - Reprise -\"",
    "64": "Deceit Sign \"Backstabber Revenge\"",
    "68": "Reverse Sign \"The Curse of Left and Right\"",
    "70": "Reverse Sign \"Mirror of Lies\"",
    "72": "Reverse Sign \"Head under Feet\"",
    "74": "Reverse Sign \"Heaven's Visit to Hell\"",
    "76": "Reverse Bow \"The Bow Shooting From Hell\"",
    "78": "Reverse Bow \"Bow of Heaven, Bow of Hell\"",
    "80": "Turnabout \"Circle of Confusion\"",
    "82": "Turnabout \"Spiral of Death\"",
    "84": "Small Bullet \"Inchling Warrior's Path\"",
    "86": "Small Bullet \"Grand Path of Warfare\"",
    "88": "Mallet \"Grow Massive!\"",
    "90": "Mallet \"Grow Even More Massive!\"",
    "92": "Bewitched Sword \"Oni-Slaying Sword\"",
    "96": "Mallet \"Titan Slayer Spell!\"",
    "100": "\"Attack on Titan\"",
    "102": "\"Protective Wall of Issun-Boshi\"",
    "104": "\"Issun and the Wolf\"",
    "106": "\"Grand Artist Issun\"",
    "108": "String Music \"Storm Ensemble\"",
    "109": "String Music \"Joururi World\"",
    "110": "First Drum \"Raging Temple Taiko\"",
    "111": "Second Drum \"Vengeful Spirit Aya-no-Tsuzumi\"",
    "112": "Third Drum \"Three Strikes at Midnight\"",
    "113": "Death Drum \"Land Percuss\"",
    "114": "Fifth Drum \"Den-Den Daiko\"",
    "115": "Sixth Drum \"Alternate Sticking\"",
    "116": "Seventh Drum \"High Speed Taiko Rocket\"",
    "117": "Eighth Drum \"Thunder God's Anger\"",
    "118": "\"Blue Lady Show\"",
    "119": "\"Pristine Beat\""
}