{
    "0": "Ice Sign \"Grand Ice Fairy Finale\"",
    "2": "Water Sign \"Underwater Whirlpool Trap\"",
    "6": "Scale Sign \"Boat Sinker\"",
    "8": "Scale Sign \"Great Waves of the Ocean\"",
    "9": "Scale Sign \"Tsunami Overwhelm\"",
    "10": "Flight Sign \"Headless Chicken\"",
    "14": "Neck Sign \"Laser Trapper\"",
    "16": "Neck Sign \"Laser Head Spinner\"",
    "18": "Flying Head \"Broken Head Trauma\"",
    "20": "Flying Head \"Multiple Head Trauma\"",
    "21": "Flying Head \"Many Brain Theory\"",
    "22": "Flying Head \"Fearful Dullahan Night\"",
    "26": "Fang Sign \"Inverted Moon Teeth\"",
    "28": "Transformation \"Transformed Triangle\"",
    "30": "Transformation \"Star Pattern\"",
    "32": "Roar \"High-Pitched Howl\"",
    "34": "Roar \"Inverted Moon Cry\"",
    "36": "Wolf Sign \"Wolf Pouncer Bouncer\"",
    "38": "Sirius \"Lightspeed Pounce\"",
    "40": "Heikyoku \"Sounds of Jetavana's Bell\"",
    "44": "Vengeful Spirit \"Hoichi the Earless\"",
    "46": "Vengeful Spirit \"Great Vengeful Spirit of Taira\"",
    "48": "Music Sign \"Wicked Musical Score\"",
    "50": "Music Sign \"Malicious Musical Score\"",
    "51": "Music Sign \"Double Score\"",
    "52": "Koto Sign \"Sounds of Anicca's Koto\"",
    "56": "Echo Sign \"Heian's Reverberation\"",
    "58": "Echo Sign \"Echo Chamber\"",
    "60": "Koto Music \"Social Upheaval Koto Music Complement\"",
    "62": "Koto Music \"Social Upheaval Requiem\"",
    "64": "Deceit Sign \"Reverse Needle Attack\"",
    "68": "Reverse Sign \"Danmaku Through the Looking-Glass\"",
    "70": "Reverse Sign \"Evil in the Mirror\"",
    "72": "Reverse Sign \"This Side Down\"",
    "74": "Reverse Sign \"Overturning All Under Heaven\"",
    "76": "Reverse Bow \"Dream Bow of Heaven & Earth\"",
    "78": "Reverse Bow \"Decree of the Dream Bow of Heaven & Earth\"",
    "80": "Turnabout \"Reverse Hierarchy\"",
    "82": "Turnabout \"Change Air Brave\"",
    "84": "Small Bullet \"Inchling's Path\"",
    "86": "Small Bullet \"Inchling's Thorny Path\"",
    "88": "Mallet \"Grow Bigger!\"",
    "90": "Mallet \"Grow Even Bigger!\"",
    "92": "Bewitched Sword \"Shining Needle Sword\"",
    "96": "Mallet \"You Grow Bigger!\"",
    "100": "\"Attack on Dwarf\"",
    "102": "\"Wall of Issun\"",
    "104": "\"Hop-o'-My-Thumb Seven\"",
    "106": "\"The Seven Issun-Boshi\"",
    "108": "String Music \"Storm Ensemble\"",
    "109": "String Music \"Joururi World\"",
    "110": "First Drum \"Raging Temple Taiko\"",
    "111": "Second Drum \"Vengeful Spirit Aya-no-Tsuzumi\"",
    "112": "Third Drum \"Three Strikes at Midnight\"",
    "113": "Death Drum \"Land Percuss\"",
    "114": "Fifth Drum \"Den-Den Daiko\"",
    "115": "Sixth Drum \"Alternate Sticking\"",
    "116": "Seventh Drum \"High Speed Taiko Rocket\"",
    "117": "Eighth Drum \"Thunder God's Anger\"",
    "118": "\"Blue Lady Show\"",
    "119": "\"Pristine Beat\""
}