{
    "2": "Nightlight Sign \"New Light Tonight\"",
    "3": "Heat Death \"Universal Darkness\"",
    "4": "Growth Sign \"Nurturing Cocoon\"",
    "5": "Shadow Sign \"Overarching Wings of Darkness\"",
    "12": "Spring Sign \"Petals of Joy and Life\"",
    "13": "Prism Sign \"Splitting Light\"",
    "14": "Spring Essence \"New Year, New Life, Reborn\"",
    "15": "Wing Sign \"Scattering Fairy Wings\"",
    "21": "History Sign \"Rewinding Beginning\"",
    "22": "Demon Sign \"Crossing Border of Makai\"",
    "23": "Flood Sign \"Great Surviving Arc\"",
    "24": "Killing Sign \"Sideswept Murder\"",
    "25": "Pharaoh Sign \"Curse Of The Sarcophagus\"",
    "26": "Maid Sign \"Memory Of Best Servant\"",
    "27": "\"Gensokyo Big Crunch -Final Judgement\"",
    "31": "Wave Sign \"Wavelength Of Sound\"",
    "32": "Trumpet Sign \"Vibrant Doot\"",
    "33": "String Sign \"4 Strings Of Harmonious Notes\"",
    "34": "Echo Sign \"Enclosed Hall Of Sounds\"",
    "35": "Violin Sign \"Reverberation Of Sounds\"",
    "36": "Piano Sign \"Keys Of Black And White\"",
    "37": "Bach Sign \"Gold-Plated Metals\"",
    "38": "Stradivarius Sign \"Wealth And Quality Products\"",
    "41": "Sun & Water Sign \"Hydrogenous Prominence\"",
    "42": "Flower Sign \"Colorful Light Lotus Flower Palm\"",
    "43": "Water & Fire Sign \"Phlogistic Rain\"",
    "44": "Colorful Flip \"Fluttering Petals and Falling Leaves\"",
    "45": "Moon & Wood Sign \"Satellite Himawari\"",
    "46": "Colorful Chinese Flower \"Rainbow Taijiquan\"",
    "47": "Sun & Moon Sign \"Royal Diamond Ring\"",
    "51": "Human Knowledge Sword \"Turning Angel Cut\"",
    "52": "Star Sign \"Leaping Kasane-Uroko Star\"",
    "53": "Obsession Sword \"Blood of Asura\"",
    "54": "Kishin \"Rumbling Jikokuten\"",
    "55": "Celestial Star Sword \"As the Silent Nirvana\"",
    "56": "Bakeneko \"Chen\"",
    "57": "Four Births Sword \"Echoes of the Inclemency of All Beings\"",
    "61": "Devil Sign \"All the World in Nightmare\"",
    "62": "Time Sign \"Tunnel Effect\"",
    "63": "Scarlet Sign \"Bloody Magic Square\"",
    "64": "Void \"Inflation Square\"",
    "65": "Scarlet Bat \"Vampirish Night\"",
    "66": "Silver Sign \"Perfect Maid\"",
    "67": "God Devil \"Remilia Stoker\"",
    "71": "Ghostly Elegance \"Light Trap of Passing Away\"",
    "72": "Esoteric Sign \"Odaishi-sama's Secret Key\"",
    "73": "Butterfly Sign \"Deadly Lance of the Swallowtail Butterfly Crest\"",
    "74": "Ascetic Sign \"Eighty Million Goma Boards\"",
    "75": "Death Sign \"Life of Drunk, Dream of Death\"",
    "76": "Superman \"Soaring En no Ozunu\"",
    "77": "\"Death Butterfly, Floating Moon\"",
    "81": "New Impossible Request \"Lunar Ilmenite\"",
    "82": "Medicine Sign \"Butterfly Dream Pill - Nightmare Type\"",
    "83": "New Impossible Request \"Red Stone of Aja\"",
    "84": "Elixir \"Mercury Sea\"",
    "85": "New Impossible Request \"Seamless Ceiling of Kinkaku-ji\"",
    "86": "Secret Elixir \"Lunar Incense\"",
    "87": "New Impossible Request \"Mysterium\"",
    "91": "Lie \"Tongue of Wolf\"",
    "92": "Death Song \"Ferry of the Deep Fog\"",
    "93": "Judgment \"Trial of the Ten Kings\"",
    "94": "Old Rain \"Rain in the Liminal Journey Through Yomi\"",
    "95": "Judgment \"Guilty or Not Guilty\"",
    "96": "Death Price \"Price of Life\"",
    "97": "Judgment \"Cleansed Crystal Judgment -Aya Shameimaru-\"",
    "100": "Taboo \"Forbidden Fruit\"",
    "101": "Taboo \"Forbidden Games\"",
    "102": "Boundary Sign \"Boundary of Form and Emptiness\"",
    "103": "Boundary Sign \"Boundary of Wave and Particle\"",
    "104": "Exalted Personage \"Forewarning of St. Germain\"",
    "105": "Hourai \"Mizunoe no Uranoshimako and Five-Colored Turtles\"",
    "106": "Ghastly Air \"Deep Fog Labyrinth\"",
    "107": "\"Night Parade of a Million Demons\""
}