{
    "2": "Nightlight Sign \"New Light Tonight\"",
    "3": "Heat Death \"Universal Darkness\"",
    "4": "Growth Sign \"Nurturing Cocoon\"",
    "5": "Shadow Sign \"Overarching Wings of Darkness\"",
    "12": "Spring Sign \"Petals of Joy and Life\"",
    "13": "Prism Sign \"Splitting Light\"",
    "14": "Spring Essence \"New Year, New Life, Reborn\"",
    "15": "Wing Sign \"Scattering Fairy Wings\"",
    "21": "History Sign \"Rewinding Beginning\"",
    "22": "Demon Sign \"Crossing Border of Makai\"",
    "23": "Flood Sign \"Great Surviving Arc\"",
    "24": "Killing Sign \"Sideswept Murder\"",
    "25": "Pharaoh Sign \"Curse Of The Sarcophagus\"",
    "26": "Maid Sign \"Memory Of Best Servant\"",
    "27": "\"Gensokyo Big Crunch -Final Judgement\"",
    "31": "Wave Sign \"Wavelength Of Sound\"",
    "32": "Trumpet Sign \"Vibrant Doot\"",
    "33": "String Sign \"4 Strings Of Harmonious Notes\"",
    "34": "Echo Sign \"Enclosed Hall Of Sounds\"",
    "35": "Violin Sign \"Reverberation Of Sounds\"",
    "36": "Piano Sign \"Keys Of Black And White\"",
    "37": "Bach Sign \"Gold-Plated Metals\"",
    "38": "Stradivarius Sign \"Wealth And Quality Products\"",
    "41": "Lucifer Sign \"Lake Of Fire\"",
    "42": "Dragon Sign \"Chaos Of Invisible Dragon Spirit\"",
    "43": "Iblis Sign \"Birth From Flames\"",
    "44": "Qi Sign \"Unblocking Chakras\"",
    "45": "Rahu Sign \"Eclipsed Sunlight\"",
    "46": "Color Sign \"Orange Sunset\"",
    "47": "Mara Sign \"Seduction Of The Self\"",
    "51": "Split Thought Sword \"Netherworld Alternate Slash\"",
    "52": "Curiosity Sign \"Reclamation Of The Table\"",
    "53": "Split Sword \"Two Blades Of The Same Metal\"",
    "54": "Sleep Sign \"Awakened Beast\"",
    "55": "Eternal Second \"Moments Before Demise\"",
    "56": "Water Sign \"Ingrained Fear\"",
    "57": "Blinding Speed \"Cuts Through Space And Time\"",
    "61": "Countdown Sign \"Count To Demise\"",
    "62": "Steamroll Sign \"Flattening Feeling\"",
    "63": "Spear Sign \"Spear The Gungnir\"",
    "64": "Murder Room II \"Escape Room Mystery\"",
    "65": "Bat Summon \"Overused Enemies\"",
    "66": "Time Sign \"Moment Of Peril\"",
    "67": "Cross Sign \"Overcoming Restriction\"",
    "71": "Forgotten Path \"Pathway To The Netherworld\"",
    "72": "Cage Sign \"Shikigami Imprisonment\"",
    "73": "Haunting Sign \"Forgotten Sin Standing Behind You\"",
    "74": "Shikigami Sign \"Even Better Buddhist\"",
    "75": "Death Sign \"Road Of Certain Doom\"",
    "76": "Hypercharge \"Perpetual Motion Machine\"",
    "77": "\"Resurrection Butterfly -Practice Round-\"",
    "81": "New Impossible Request \"Lunar Ilmenite\"",
    "82": "Medicine Sign \"Butterfly Dream Pill - Nightmare Type\"",
    "83": "New Impossible Request \"Red Stone of Aja\"",
    "84": "Elixir \"Mercury Sea\"",
    "85": "New Impossible Request \"Seamless Ceiling of Kinkaku-ji\"",
    "86": "Secret Elixir \"Lunar Incense\"",
    "87": "New Impossible Request \"Mysterium\"",
    "91": "Lie \"Tongue of Wolf\"",
    "92": "Death Song \"Ferry of the Deep Fog\"",
    "93": "Judgment \"Trial of the Ten Kings\"",
    "94": "Old Rain \"Rain in the Liminal Journey Through Yomi\"",
    "95": "Judgment \"Guilty or Not Guilty\"",
    "96": "Death Price \"Price of Life\"",
    "97": "Judgment \"Cleansed Crystal Judgment -Aya Shameimaru-\"",
    "100": "Taboo \"Forbidden Fruit\"",
    "101": "Taboo \"Forbidden Games\"",
    "102": "Boundary Sign \"Boundary of Form and Emptiness\"",
    "103": "Boundary Sign \"Boundary of Wave and Particle\"",
    "104": "Exalted Personage \"Forewarning of St. Germain\"",
    "105": "Hourai \"Mizunoe no Uranoshimako and Five-Colored Turtles\"",
    "106": "Ghastly Air \"Deep Fog Labyrinth\"",
    "107": "\"Night Parade of a Million Demons\""
}