{
    "2": "Firefly Sign \"Fading Star of Tomorrow\"",
    "3": "Darkness Sign \"Moon Cast In Shadow\"",
    "4": "Butterfly Sign \"Butterfly Army\"",
    "5": "Night Sign \"Prey of Bird\"",
    "12": "Snow Sign \"Cold Sleep\"",
    "13": "Yuki-onna Sign \"Snowy Mountain\"",
    "14": "Freeze Sign \"Negative Kelvin\"",
    "15": "Winter Sign \"Forgotten Flower\"",
    "21": "Light Sign \"Celestial Firework\"",
    "22": "Puppeteer Sign \"Benefit of Marine Life\"",
    "23": "Shroud Sign \"Torrential Perception\"",
    "24": "Curse Sign \"Black Powder Dolls\"",
    "25": "Hollyhock Sign \"Mitori's Full-Stop\"",
    "26": "Red Sign \"Scarlet Dolls Embodiment\"",
    "27": "Japan Sign \"Great Robot of Yamato\"",
    "31": "Fog Sign \"Gas Giant\"",
    "32": "Runaway Rabbit \"Tricksters Escape Route\"",
    "33": "Spread Sign \"Great War on Lunatic Front\"",
    "34": "Poison Sign \"Wind of Lethal Poison\"",
    "35": "Impact Sign \"Crater-filled Moon\"",
    "36": "Confusion \"Poison Coma\"",
    "37": "Owing Sign \"The Best Prank Ever\"",
    "38": "Mad Dream \"Illusion of Nightmarish Dream\"",
    "41": "Sun & Water Sign \"High-Level Evaporation\"",
    "42": "Flower Sign \"Beautiful Dream Flower\"",
    "43": "Water & Fire Sign \"Phoenix Wings of Water\"",
    "44": "Colorful Flip \"Scattering Autumn Leaves\"",
    "45": "Moon & Wood Sign \"Sattelite in Orbit\"",
    "46": "Colorful Chinese Flower \"Double Rainbow Effect\"",
    "47": "Sun & Moon Sign \"Engagement Ring for a Princess\"",
    "51": "Human Knowledge Sword \"Time-Slowing Slash\"",
    "52": "Star Sign \"Shooting Star of Netherworld\"",
    "53": "Obsession Sword \"Bloodflow of Time\"",
    "54": "Kishin \"Earthquake in Mayohiga\"",
    "55": "Celestial Star Sword \"Silence of the Dead\"",
    "56": "Supercat \"Chen\"",
    "57": "Four Births Sword \"Double-Crossed Sword Technique\"",
    "61": "Devil Sign \"Nightmare Vision\"",
    "62": "Time Sign \"Warped Time Perspective\"",
    "63": "Scarlet Sign \"Bloody Mystic Square\"",
    "64": "Void \"Eternal Time Loop\"",
    "65": "Scarlet Bat \"Lord of Bats\"",
    "66": "Silver Sign \"Perfect Maid - Sakuya Izayoi\"",
    "67": "God Devil \"Remilia Tepes\"",
    "71": "Ghostly Elegance \"Non-Ghost Repellant\"",
    "72": "Esoteric Sign \"Key-Shaped Tomb\"",
    "73": "Butterfly Sign \"Death-Defying Stab\"",
    "74": "Ascetic Sign \"Yakumo's Perfect Guard\"",
    "75": "Death Sign \"The Eternal Drunken Dream\"",
    "76": "Superman \"Lightspeed Shikigami\"",
    "77": "\"Death And Suffering, Even In Dream\"",
    "81": "New Impossible Nightmare \"Endless Moon\"",
    "82": "Medicine Sign \"Endless Sleeping Pill\"",
    "83": "New Impossible Nightmare \"Perfect Mask - Red Stone\"",
    "84": "Elixir \"Mercury Waterfall\"",
    "85": "New Impossible Nightmare \"Return of Seamless Ceiling\"",
    "86": "Secret Elixir \"Dream Laser\"",
    "87": "New Impossible Nightmare \"Mysterious Nightshade\"",
    "91": "Lie \"The Sin of Lying\"",
    "92": "Death Song \"Deathscythe Paradise\"",
    "93": "Judgment \"Highest Court of Judges\"",
    "94": "Old Rain \"Rainy Ferry over Higan\"",
    "95": "Judgment \"Guilty and Prosecuted\"",
    "96": "Death Price \"High-Stake Life Calculations\"",
    "97": "Dream Summon \"Dream Dweller - Aya Shameimeru\"",
    "100": "Taboo \"Frantically Forbidden Fruit\"",
    "101": "Taboo \"Bubbles of Imaginary Death\"",
    "102": "Boundary Sign \"Boundary of Death and Afterlife\"",
    "103": "Boundary Sign \"Boundary of Lucid Dream and Waking Nightmare\"",
    "104": "Exalted Personage \"Lost Person of Hourai\"",
    "105": "Hourai \"The Multicolored Moon\"",
    "106": "Ghastly Air \"Drunken Oni Breath\"",
    "107": "\"Planet-Crushing Oni Dance\""
}